# Generated by Django 5.2.11 on 2026-02-26 02:28
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('core', '0039_add_reopen_fields'),
    ]
    operations = [
        migrations.RenameIndex(
            model_name='entitychartofaccount',
            new_name='core_entity_entity__d39aed_idx',
            old_name='core_entityc_entity__idx_sec',
        ),
        migrations.RenameIndex(
            model_name='entitychartofaccount',
            new_name='core_entity_entity__86dcdf_idx',
            old_name='core_entityc_entity__idx_act',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('login', 'User Login'), ('logout', 'User Logout'), ('import', 'Data Import'), ('adjustment', 'Adjustment Created'), ('generate', 'Document Generated'), ('status_change', 'Status Changed'), ('mapping_change', 'Mapping Changed'), ('user_change', 'User Modified'), ('template_change', 'Template Modified'), ('ai_feedback', 'AI Feedback'), ('reopen', 'Year Reopened')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_code',
            field=models.CharField(help_text='Account code, e.g. "500", "1510", "2000.01"', max_length=20),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('trust', 'Trust'), ('partnership', 'Partnership'), ('sole_trader', 'Sole Trader'), ('smsf', 'SMSF')], help_text='Restrict to a specific entity type, or leave blank for all.', max_length=20),
        ),
        migrations.AlterField(
            model_name='entitychartofaccount',
            name='account_code',
            field=models.CharField(help_text='Account code, e.g. "500", "1510", "2000.01"', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxplanningbeneficiaryrow',
            name='beneficiary',
            field=models.ForeignKey(help_text='From Directors/Trustees/Beneficiaries tab', on_delete=django.db.models.deletion.CASCADE, related_name='tax_planning_rows', to='core.entityofficer'),
        ),
    ]
