# Generated by Django 5.2.11 on 2026-02-26 02:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_rename_core_entityc_entity__idx_sec_core_entity_entity__d39aed_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialbalanceline',
            name='source',
            field=models.CharField(blank=True, choices=[('tb_import', 'Trial Balance Import'), ('bank_statement', 'Bank Statement'), ('manual_journal', 'Manual Journal'), ('journal_upload', 'Journal Upload'), ('rollover', 'Rolled Forward')], default='tb_import', help_text='Where this line originated from', max_length=20),
        ),
        migrations.CreateModel(
            name='BulkJournalUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, help_text='Auto-generated sequential reference, e.g. Bulk JNLS-001', max_length=30)),
                ('filename', models.CharField(blank=True, help_text='Original uploaded filename', max_length=255)),
                ('description', models.CharField(blank=True, default='Bulk Journal Upload', max_length=500)),
                ('lines_count', models.IntegerField(default=0, help_text='Number of journal lines in this upload')),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, help_text='Total debit amount across all lines', max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, help_text='Total credit amount across all lines', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_journal_uploads', to='core.financialyear')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_journal_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Journal Upload',
                'verbose_name_plural': 'Bulk Journal Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='trialbalanceline',
            name='bulk_journal_upload',
            field=models.ForeignKey(blank=True, help_text='Links this adjustment line to its parent bulk journal upload', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_balance_lines', to='core.bulkjournalupload'),
        ),
    ]
