# Generated by Django 5.2.11 on 2026-02-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_bas_period_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='gst_registration_date',
            field=models.DateField(blank=True, help_text='Date the entity registered for GST.', null=True),
        ),
    ]
