# Generated by Django 5.2.11 on 2026-02-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_bas_period_redesign'),
    ]

    operations = [
        # Field already added by 0044_eva_ai_compliance_reviewer — no-op to avoid
        # duplicate column error on SQLite (which cannot use IF NOT EXISTS).
    ]
