# Generated by Django 5.2.11 on 2026-02-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_entity_gst_registration_date'),
        ('core', '0045_eva_v2_knowledge_brain_chat'),
    ]

    operations = [
    ]
