# Generated by Django 5.2.11 on 2026-02-27 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_merge_20260227_1045'),
    ]

    operations = [
        # RenameIndex operations removed — the old_name values referenced
        # index names that were never created (migration 0044/0045 used
        # different names).  Keeping as no-op to preserve migration history.
    ]
