# Generated by Django 5.2.11 on 2026-02-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_rename_core_evaconvo_fy_user_idx_core_evacon_financi_652320_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='industry',
            field=models.CharField(choices=[('accounting', 'Accounting & Tax Services'), ('legal', 'Legal Services'), ('consulting', 'Management Consulting'), ('it_services', 'IT & Technology Services'), ('engineering', 'Engineering Services'), ('architecture', 'Architecture & Design'), ('financial_services', 'Financial Services & Planning'), ('real_estate', 'Real Estate & Property Services'), ('marketing', 'Marketing & Advertising'), ('professional_other', 'Other Professional Services'), ('medical_gp', 'Medical — General Practice'), ('medical_specialist', 'Medical — Specialist'), ('dental', 'Dental'), ('allied_health', 'Allied Health (Physio, Chiro, etc.)'), ('pharmacy', 'Pharmacy'), ('veterinary', 'Veterinary'), ('healthcare_other', 'Other Healthcare'), ('construction', 'Construction — Builder'), ('electrical', 'Electrical Contractor'), ('plumbing', 'Plumbing Contractor'), ('trades_other', 'Other Trades & Contracting'), ('restaurant', 'Restaurant & Cafe'), ('hotel', 'Hotel & Accommodation'), ('catering', 'Catering'), ('food_manufacturing', 'Food Manufacturing'), ('hospitality_other', 'Other Hospitality'), ('retail', 'Retail — General'), ('ecommerce', 'E-Commerce & Online Retail'), ('wholesale', 'Wholesale & Distribution'), ('transport', 'Transport & Logistics'), ('courier', 'Courier & Delivery'), ('agriculture', 'Agriculture & Farming'), ('mining', 'Mining & Resources'), ('fishing', 'Fishing & Aquaculture'), ('manufacturing', 'Manufacturing — General'), ('nfp_charity', 'Not-for-Profit — Charity'), ('nfp_association', 'Not-for-Profit — Association'), ('nfp_other', 'Not-for-Profit — Other'), ('education', 'Education & Training'), ('childcare', 'Childcare'), ('property_investment', 'Property Investment'), ('investment', 'Investment & Holding Company'), ('smsf_industry', 'SMSF / Superannuation'), ('beauty', 'Beauty & Personal Care'), ('fitness', 'Fitness & Recreation'), ('cleaning', 'Cleaning Services'), ('security', 'Security Services'), ('other', 'Other')], default='', help_text='Industry classification — used by Eva for AI analysis, GST coding, and benchmarking.', max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('login', 'User Login'), ('logout', 'User Logout'), ('import', 'Data Import'), ('adjustment', 'Adjustment Created'), ('generate', 'Document Generated'), ('status_change', 'Status Changed'), ('mapping_change', 'Mapping Changed'), ('user_change', 'User Modified'), ('template_change', 'Template Modified'), ('ai_feedback', 'AI Feedback'), ('reopen', 'Year Reopened'), ('eva_chat', 'Eva Chat'), ('eva_review', 'Eva Review'), ('eva_finding', 'Eva Finding'), ('eva_sync', 'Eva Knowledge Sync')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('reviewed', 'Reviewed'), ('prepared', 'Prepared (Eva Reviewing)'), ('pending_eva', 'Pending Eva Review'), ('eva_cleared', 'Eva Cleared'), ('eva_error', 'Eva Error'), ('finalised', 'Finalised')], default='draft', max_length=20),
        ),
    ]
