# Generated by Django 5.2.11 on 2026-02-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_rename_reviewed_to_finished'),
        ('core', '0048_entity_industry_alter_auditlog_action_and_more'),
    ]

    operations = [
    ]
