# Generated by Django 5.2.11 on 2026-03-01 09:00
#
# This migration adds only what 0050 and earlier migrations do NOT cover:
# - 2 new models: ActivityLog, EntityRelationship
# - Entity registered address fields (5 fields)
# - FinancialYear.reopened_at, reopened_by
# - LegalDocument.title, context_data, 'generated' status choice
# - GoverningDocument.is_primary

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_distributionscenario_entity_appointor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── 1. ActivityLog already created in 0015 — skipped.

        # ── 2. Create EntityRelationship ───────────────────────────
        migrations.CreateModel(
            name='EntityRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[
                    ('trustee_of', 'Trustee Of'),
                    ('beneficiary_of', 'Beneficiary Of'),
                    ('shareholder_of', 'Shareholder Of'),
                    ('partner_of', 'Partner Of'),
                    ('related_entity', 'Related Entity'),
                    ('subsidiary_of', 'Subsidiary Of'),
                    ('parent_of', 'Parent Of'),
                ], max_length=20)),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('units_held', models.PositiveIntegerField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='core.entity')),
                ('to_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='core.entity')),
            ],
            options={
                'ordering': ['relationship_type'],
                'unique_together': {('from_entity', 'to_entity', 'relationship_type')},
            },
        ),

        # ── 3. Entity registered address fields ───────────────────
        migrations.AddField(
            model_name='entity',
            name='registered_address_line1',
            field=models.CharField(blank=True, default='', help_text='Registered office address line 1', max_length=255),
        ),
        migrations.AddField(
            model_name='entity',
            name='registered_address_line2',
            field=models.CharField(blank=True, default='', help_text='Registered office address line 2', max_length=255),
        ),
        migrations.AddField(
            model_name='entity',
            name='registered_address_city',
            field=models.CharField(blank=True, default='', help_text='Registered office suburb/city', max_length=100),
        ),
        migrations.AddField(
            model_name='entity',
            name='registered_address_state',
            field=models.CharField(blank=True, default='', help_text='Registered office state (e.g. VIC, NSW)', max_length=10),
        ),
        migrations.AddField(
            model_name='entity',
            name='registered_address_postcode',
            field=models.CharField(blank=True, default='', help_text='Registered office postcode', max_length=10),
        ),

        # ── 4. FinancialYear reopen fields — already in 0039, skipped.

        # ── 5. LegalDocument.title and context_data ────────────────
        migrations.AddField(
            model_name='legaldocument',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Human-readable document title', max_length=500),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='context_data',
            field=models.JSONField(blank=True, default=dict, help_text='Full context data used for document rendering'),
        ),

        # ── 6. LegalDocument status — add 'generated' choice ──────
        migrations.AlterField(
            model_name='legaldocument',
            name='status',
            field=models.CharField(choices=[
                ('draft', 'Draft'),
                ('generated', 'Generated'),
                ('final', 'Final'),
                ('executed', 'Executed'),
            ], default='draft', max_length=10),
        ),

        # ── 7. GoverningDocument.is_primary ────────────────────────
        migrations.AddField(
            model_name='governingdocument',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Whether this is the primary operative document for the entity'),
        ),

        # ── 8. Indexes ────────────────────────────────────────────
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['entity', '-created_at'], name='core_activi_entity__a1b2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['financial_year', '-created_at'], name='core_activi_financi_d4e5f6_idx'),
        ),
    ]
