# Generated by Django 5.2.11 on 2026-03-02 05:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_reclassify_3565_and_2950'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ASICReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_type', models.CharField(choices=[('annual_return', 'ASIC Annual Return'), ('business_name', 'Business Name Renewal'), ('company_change', 'Company Change'), ('deregistration', 'Deregistration'), ('other', 'Other')], default='annual_return', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('lodged', 'Lodged'), ('burning', 'Burning'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fee amount if applicable.', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_lodged', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['due_date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='BASPeriodCommentary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(help_text='Start date of the commentary period')),
                ('period_end', models.DateField(help_text='End date of the commentary period')),
                ('period_label', models.CharField(blank=True, default='', help_text="Human-readable period label, e.g. 'Q1 (Jul-Sep 2025)'", max_length=50)),
                ('section_snapshot', models.TextField(blank=True, default='', help_text='Section 1: Period Snapshot (2-3 sentences, revenue headline)')),
                ('section_revenue', models.TextField(blank=True, default='', help_text='Section 2: Revenue Analysis (2-3 significant movements)')),
                ('section_costs', models.TextField(blank=True, default='', help_text='Section 3: Cost & Margin Analysis (gross margin, opex trends)')),
                ('section_watch_items', models.TextField(blank=True, default='', help_text='Section 4: Items to Watch (max 4 items, plain English)')),
                ('section_actions', models.TextField(blank=True, default='', help_text='Section 5: Recommended Actions (1-3 specific actions)')),
                ('full_content', models.TextField(blank=True, default='', help_text='Complete rendered commentary content (all sections combined)')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('draft', 'Draft'), ('reviewed', 'Reviewed'), ('sent', 'Sent to Client'), ('error', 'Error')], default='generating', max_length=12)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('conversational', 'Conversational'), ('technical', 'Technical')], default='professional', max_length=15)),
                ('version', models.PositiveIntegerField(default=1)),
                ('model_used', models.CharField(blank=True, default='', help_text='AI model tier used: haiku/sonnet/opus', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('context_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of the financial data used to generate this commentary')),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'BAS Period Commentary',
                'verbose_name_plural': 'BAS Period Commentaries',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10)),
                ('correspondence_type', models.CharField(choices=[('ato_notice', 'ATO Notice'), ('noa_refund', 'NOA — Refund'), ('noa_payable', 'NOA — Payable'), ('tax_documents', 'Tax Documents'), ('letter_payable', 'Letter — Payable'), ('document_request', 'Document Request'), ('fusesign_bundle', 'FuseSign Bundle'), ('client_letter', 'Client Letter'), ('asic_notice', 'ASIC Notice'), ('bank_statement', 'Bank Statement'), ('other', 'Other')], default='other', max_length=30)),
                ('subject', models.CharField(blank=True, help_text='Brief description of the correspondence.', max_length=500)),
                ('status', models.CharField(choices=[('received', 'Received'), ('sent', 'Sent'), ('pending', 'Pending'), ('awaiting', 'Awaiting Reply'), ('actioned', 'Actioned'), ('filed', 'Filed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or context.')),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('date_actioned', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'correspondence',
                'ordering': ['-date_received', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('one_off', 'One-off')], default='daily', max_length=10)),
                ('scheduled_time', models.TimeField(blank=True, help_text='Suggested time for this task.', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in the checklist.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this task appears in the checklist.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyTaskCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_date', models.DateField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-completed_date'],
            },
        ),
        migrations.CreateModel(
            name='DebtorRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('amount_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('days_overdue', models.IntegerField(default=0)),
                ('escalation_stage', models.CharField(choices=[('current', 'Current'), ('1st_statement', '1st Statement'), ('2nd_statement', '2nd Statement'), ('soft_letter', 'Soft Letter'), ('firm_letter', 'Firm Letter'), ('final_notice', 'Final Notice'), ('write_off', 'Write Off')], default='current', max_length=20)),
                ('status', models.CharField(choices=[('current', 'Current'), ('overdue', 'Overdue'), ('payment_plan', 'Payment Plan'), ('paid', 'Paid'), ('written_off', 'Written Off')], default='current', max_length=20)),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-days_overdue', '-amount_outstanding'],
            },
        ),
        migrations.CreateModel(
            name='NOARecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('noa_type', models.CharField(choices=[('refund', 'Refund'), ('payable', 'Payable'), ('nil', 'Nil')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('to_send', 'To Send'), ('sent', 'Sent to Client'), ('forwarded', 'Forwarded to Accountant'), ('actioned', 'Actioned')], default='to_send', max_length=20)),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('date_sent', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NOA Record',
                'verbose_name_plural': 'NOA Records',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('instalment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly')], default='monthly', max_length=15)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='active', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_payment_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='entityrelationship',
            options={'ordering': ['relationship_type', 'to_entity']},
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='core_activi_entity__a1b2c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='core_activi_financi_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='bankaccountmapping',
            new_name='core_bankac_entity__494cb7_idx',
            old_name='core_bankac_entity__idx',
        ),
        migrations.RenameIndex(
            model_name='evafinding',
            new_name='core_evafin_eva_rev_8cc8a8_idx',
            old_name='core_evafin_eva_rev_idx',
        ),
        migrations.RenameIndex(
            model_name='evamessage',
            new_name='core_evames_convers_38df75_idx',
            old_name='core_evamsg_convo_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='evareview',
            new_name='core_evarev_financi_526c62_idx',
            old_name='core_evarev_financi_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgechunk',
            new_name='core_knowle_documen_8ab2a7_idx',
            old_name='core_knowchunk_doc_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgedocument',
            new_name='core_knowle_categor_577ad1_idx',
            old_name='core_knowdoc_cat_sync_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgedocument',
            new_name='core_knowle_sharepo_a78fde_idx',
            old_name='core_knowdoc_sp_item_idx',
        ),
        # RemoveField activitylog.metadata skipped — field was never
        # created (the duplicate CreateModel in 0051 was removed).
        migrations.RemoveField(
            model_name='entity',
            name='registered_address_city',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='registered_address_line1',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='registered_address_line2',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='registered_address_postcode',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='registered_address_state',
        ),
        migrations.RemoveField(
            model_name='entityrelationship',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='entityrelationship',
            name='ownership_percentage',
        ),
        migrations.RemoveField(
            model_name='entityrelationship',
            name='units_held',
        ),
        # AddField activitylog.is_read / title / url skipped —
        # these fields already exist from 0015_activitylog.
        migrations.AddField(
            model_name='entity',
            name='commentary_frequency_override',
            field=models.CharField(choices=[('match_bas', 'Match BAS Frequency'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('annual', 'Annual Only')], default='match_bas', help_text="Override the default commentary generation frequency. 'Match BAS' uses the entity's BAS frequency.", max_length=15),
        ),
        migrations.AddField(
            model_name='entity',
            name='trustee_acn',
            field=models.CharField(blank=True, default='', help_text='ACN of the trustee company (trusts and SMSFs only)', max_length=9, verbose_name='Trustee ACN'),
        ),
        migrations.AddField(
            model_name='entity',
            name='trustee_name',
            field=models.CharField(blank=True, default='', help_text='Trustee company name (trusts and SMSFs only)', max_length=255),
        ),
        migrations.AddField(
            model_name='entityrelationship',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evafinding',
            name='prior_finding',
            field=models.ForeignKey(blank=True, help_text="Link to the prior review's finding that this re-opens or supersedes", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor_findings', to='core.evafinding'),
        ),
        migrations.AddField(
            model_name='evafinding',
            name='related_findings',
            field=models.ManyToManyField(blank=True, help_text='Other findings in this review that cover overlapping issues', to='core.evafinding'),
        ),
        migrations.AddField(
            model_name='evafinding',
            name='remediation_authority',
            field=models.TextField(blank=True, default='', help_text='Authoritative guidance (ATO, legislation) for this finding'),
        ),
        migrations.AddField(
            model_name='evafinding',
            name='source',
            field=models.CharField(choices=[('risk_engine', 'Risk Engine'), ('eva_analysis', 'Eva Analysis')], default='eva_analysis', help_text="Whether this finding originated from the risk engine or Eva's LLM analysis", max_length=15),
        ),
        migrations.AddField(
            model_name='evamessage',
            name='is_proactive',
            field=models.BooleanField(default=False, help_text='Whether this message was proactively generated by Eva (not in response to a user question)'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('bank_upload', 'Bank Statement Uploaded'), ('classify_complete', 'AI Classification Complete'), ('classify_started', 'AI Classification Started'), ('tb_import', 'Trial Balance Imported'), ('journal_posted', 'Journal Entry Posted'), ('year_finalised', 'Financial Year Finalised'), ('audit_run', 'Audit Risk Analysis Run'), ('review_approved', 'Transactions Approved'), ('doc_generated', 'Document Generated'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='entity',
            name='gst_registration_date',
            field=models.DateField(blank=True, help_text='Date GST registration commenced. Transactions before this date are auto-set to Out of Scope.', null=True),
        ),
        migrations.AlterField(
            model_name='entityrelationship',
            name='from_entity',
            field=models.ForeignKey(help_text='The entity this relationship originates from', on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='core.entity'),
        ),
        migrations.AlterField(
            model_name='entityrelationship',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about this relationship'),
        ),
        migrations.AlterField(
            model_name='entityrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('trustee_of', 'Trustee of'), ('beneficiary_of', 'Beneficiary of'), ('director_of', 'Director of'), ('shareholder_of', 'Shareholder of'), ('partner_in', 'Partner in'), ('parent_entity', 'Parent Entity'), ('subsidiary', 'Subsidiary'), ('associated_entity', 'Associated Entity'), ('other', 'Other')], default='associated_entity', max_length=50),
        ),
        migrations.AlterField(
            model_name='entityrelationship',
            name='to_entity',
            field=models.ForeignKey(help_text='The entity this relationship points to', on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='core.entity'),
        ),
        migrations.AlterField(
            model_name='evafinding',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('addressed', 'Addressed'), ('closed', 'Closed'), ('reopened', 'Re-Opened')], default='open', max_length=15),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='reopened_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last reopen action', null=True),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='reopened_by',
            field=models.ForeignKey(blank=True, help_text='User who last reopened this financial year', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='document_type',
            field=models.CharField(choices=[('financial_statements', 'Financial Statements'), ('distribution_minutes', 'Distribution Minutes'), ('beneficiary_statement', 'Beneficiary Statement'), ('partner_statement', 'Partner Statement'), ('trust_election', 'Trust Election (s97)'), ('tax_planning_summary', 'Tax Planning Summary'), ('workpaper_notes', 'Working Paper Notes'), ('bas_commentary', 'BAS Period Commentary'), ('other', 'Other')], default='financial_statements', max_length=30),
        ),
        migrations.AlterField(
            model_name='governingdocument',
            name='document_type',
            field=models.CharField(choices=[('trust_deed', 'Trust Deed'), ('company_constitution', 'Company Constitution'), ('partnership_agreement', 'Partnership Agreement'), ('smsf_deed', 'SMSF Deed'), ('amendment', 'Amendment'), ('supplementary', 'Supplementary Document')], max_length=30),
        ),
        migrations.AlterField(
            model_name='governingdocument',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Whether this is the primary operative document'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='context_data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured context data used for rendering'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Human-readable document title', max_length=255),
        ),
        migrations.AlterField(
            model_name='trustelectionrecord',
            name='status',
            field=models.CharField(choices=[('in_place', 'In Place'), ('not_in_place', 'Not In Place'), ('required_not_yet_made', 'Required — Not Yet Made'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=25),
        ),
        # AddIndex activitylog user/is_read indexes skipped —
        # already created by 0015_activitylog.
        migrations.AddField(
            model_name='asicreturn',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asic_returns', to='core.entity'),
        ),
        migrations.AddField(
            model_name='asicreturn',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_asic_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basperiodcommentary',
            name='bas_period',
            field=models.ForeignKey(blank=True, help_text='Specific BAS period this commentary covers. Null for custom date ranges.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='core.basperiod'),
        ),
        migrations.AddField(
            model_name='basperiodcommentary',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bas_commentaries', to='core.financialyear'),
        ),
        migrations.AddField(
            model_name='basperiodcommentary',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_bas_commentaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basperiodcommentary',
            name='legal_document',
            field=models.ForeignKey(blank=True, help_text='Generated Word document for this commentary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bas_commentaries', to='core.legaldocument'),
        ),
        migrations.AddField(
            model_name='basperiodcommentary',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bas_commentaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Staff member this correspondence has been passed to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_correspondence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='entity',
            field=models.ForeignKey(blank=True, help_text='The entity this correspondence relates to (optional for general mail).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence', to='core.entity'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_correspondence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailytaskcompletion',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailytaskcompletion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.dailytask'),
        ),
        migrations.AddField(
            model_name='debtorrecord',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_records', to='core.entity'),
        ),
        migrations.AddField(
            model_name='debtorrecord',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_debtors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noarecord',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noa_records', to='core.entity'),
        ),
        migrations.AddField(
            model_name='noarecord',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_noas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='core.entity'),
        ),
        migrations.AddIndex(
            model_name='basperiodcommentary',
            index=models.Index(fields=['financial_year', 'status'], name='core_basper_financi_1ddc50_idx'),
        ),
        migrations.AddIndex(
            model_name='basperiodcommentary',
            index=models.Index(fields=['bas_period'], name='core_basper_bas_per_0314bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailytaskcompletion',
            unique_together={('task', 'completed_date')},
        ),
    ]
