# Generated by Django 5.2.11 on 2026-03-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_asicreturn_basperiodcommentary_correspondence_and_more'),
        ('core', '0058_basperiodcommentary_prior_commentary_and_activity_log_events'),
    ]

    operations = [
    ]
