# Generated by Django 5.2.12 on 2026-03-05 10:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_depreciationasset_account_mapping_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPaperTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name, e.g. "BAS Reconciliation — Quarterly"', max_length=255)),
                ('category', models.CharField(choices=[('bas_reconciliation', 'BAS Reconciliation'), ('journal_workpaper', 'Journal Work Paper'), ('account_reconciliation', 'Account Reconciliation'), ('division_7a', 'Division 7A'), ('loan_account', 'Loan Account Schedule'), ('depreciation', 'Depreciation Schedule'), ('stock_take', 'Stock Take / Inventory'), ('payroll', 'Payroll Reconciliation'), ('trust_distribution', 'Trust Distribution Work Paper'), ('general', 'General')], default='general', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Brief description of what this work paper is used for.')),
                ('template_file', models.FileField(help_text='Upload the Excel (.xlsx) or Word (.docx) template file.', upload_to='workpaper_templates/')),
                ('file_format', models.CharField(choices=[('xlsx', 'Excel (.xlsx)'), ('docx', 'Word (.docx)')], default='xlsx', help_text='File format of the uploaded template.', max_length=4)),
                ('entity_types', models.JSONField(blank=True, default=list, help_text='List of entity types this template applies to (leave empty for all).')),
                ('is_active', models.BooleanField(default=True, help_text='Only active templates are shown in the Work Papers tab.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls display order within a category (lower = first).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work Paper Template',
                'verbose_name_plural': 'Work Paper Templates',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='div7aassessment',
            new_name='core_div7aa_financi_3afe29_idx',
            old_name='core_div7aa_financi_idx',
        ),
        migrations.RenameIndex(
            model_name='div7acompliance',
            new_name='core_div7ac_entity__2b635b_idx',
            old_name='core_div7ac_entity_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('bank_upload', 'Bank Statement Uploaded'), ('classify_complete', 'AI Classification Complete'), ('classify_started', 'AI Classification Started'), ('tb_import', 'Trial Balance Imported'), ('journal_posted', 'Journal Entry Posted'), ('year_finalised', 'Financial Year Finalised'), ('audit_run', 'Audit Risk Analysis Run'), ('review_approved', 'Transactions Approved'), ('doc_generated', 'Document Generated'), ('mgmt_accts_gen', 'Management Accounts Generated'), ('bas_commentary_generated', 'BAS Commentary Generated'), ('bas_commentary_edited', 'BAS Commentary Edited'), ('bas_commentary_regenerated', 'BAS Commentary Regenerated'), ('bas_commentary_sent', 'BAS Commentary Sent'), ('bas_commentary_deleted', 'BAS Commentary Deleted'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='div7aassessment',
            name='financial_year',
            field=models.OneToOneField(help_text='Unique per FY — one Div 7A assessment per entity per year', on_delete=django.db.models.deletion.CASCADE, related_name='div7a_assessment', to='core.financialyear'),
        ),
        migrations.AlterField(
            model_name='div7aassessment',
            name='rules_fired',
            field=models.JSONField(blank=True, default=list, help_text="Array of triggered rule IDs e.g. ['T2-D7A-01', 'T2-D7A-04']"),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='document_type',
            field=models.CharField(choices=[('financial_statements', 'Financial Statements'), ('distribution_minutes', 'Distribution Minutes'), ('beneficiary_statement', 'Beneficiary Statement'), ('partner_statement', 'Partner Statement'), ('trust_election', 'Trust Election (s97)'), ('tax_planning_summary', 'Tax Planning Summary'), ('workpaper_notes', 'Working Paper Notes'), ('bas_commentary', 'BAS Period Commentary'), ('management_accounts', 'Management Accounts'), ('other', 'Other')], default='financial_statements', max_length=30),
        ),
        migrations.AddField(
            model_name='workpapertemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workpaper_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
