# Generated by Django 5.2.11 on 2026-03-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_trialbalanceline_source_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaclarification',
            name='learning_note',
            field=models.TextField(blank=True, default='', help_text='Note stored for future reviews (e.g. borrower is a related company)'),
        ),
        migrations.AlterField(
            model_name='evaclarification',
            name='outcome_hint',
            field=models.CharField(blank=True, default='', help_text='Outcome hint from the option definition (dismiss/confirm/reduce_severity)', max_length=20),
        ),
    ]
