# Generated by Django 5.2.11 on 2026-03-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_evaclarification_learning_note_and_more'),
        ('core', '0069_financialyear_reopened_status'),
    ]

    operations = [
    ]
