# Generated by Django 5.2.11 on 2026-03-11 00:37

import config.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_financialyear_reopened_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="contact_phone",
            field=config.encryption.EncryptedCharField(
                blank=True, help_text="Primary contact phone for this entity"
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="tfn",
            field=config.encryption.EncryptedCharField(
                blank=True,
                help_text="Tax File Number (encrypted at rest)",
                verbose_name="TFN",
            ),
        ),
        migrations.AlterField(
            model_name="evaclarification",
            name="learning_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Note stored for future reviews (e.g. borrower is a related company)",
            ),
        ),
        migrations.AlterField(
            model_name="evaclarification",
            name="outcome_hint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Outcome hint from the option definition (dismiss/confirm/reduce_severity)",
                max_length=20,
            ),
        ),
    ]
