# Generated by Django 5.2.11 on 2026-03-11 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_entity_contact_phone_alter_entity_tfn_and_more'),
        ('core', '0070_merge_20260310_2346'),
    ]

    operations = [
    ]
