# Generated by Django 5.2.11 on 2026-03-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_alter_entity_contact_phone_alter_entity_tfn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="is_small_business_entity",
            field=models.BooleanField(
                blank=True,
                help_text="Companies only: whether this entity qualifies as a small business entity under the ATO definition.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="is_base_rate_entity",
            field=models.BooleanField(
                blank=True,
                help_text="Companies only: True = 25% base rate entity, False = 30% non-base rate. Used in tax calculations.",
                null=True,
            ),
        ),
    ]
