# Generated by Django 5.2.11 on 2026-03-11 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_entity_is_small_business_entity_and_more'),
        ('core', '0071_merge_20260311_1214'),
    ]

    operations = [
    ]
