# Generated by Django 5.2.11 on 2026-03-11 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_merge_20260311_1344'),
        ('core', '0073_clean_stale_eva_findings'),
    ]

    operations = [
    ]
