# Generated by Django 5.2.11 on 2026-03-11 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_merge_20260311_1440'),
        ('core', '0075_trialbalanceline_eva_flags'),
    ]

    operations = [
    ]
