# Generated by Django 5.2.11 on 2026-03-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_merge_20260311_1527'),
        ('core', '0078_alter_financialyear_status_choices'),
    ]

    operations = [
    ]
