# Generated by Django 5.2.11 on 2026-03-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_merge_20260311_1707"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adjustingjournal",
            name="journal_type",
            field=models.CharField(
                choices=[
                    ("general", "General Journal"),
                    ("adjusting", "Adjusting Entry"),
                    ("year_end", "Year-End Entry"),
                    ("depreciation", "Depreciation Entry"),
                    ("tax", "Tax Adjustment"),
                    ("tax_provision", "Tax Provision"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
