# Generated by Django 5.2.11 on 2026-03-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_add_tax_provision_journal_type"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="evaconversation",
            new_name="core_evacon_financi_652320_idx",
            old_name="core_evaconvo_fy_user_idx",
        ),
        migrations.AddField(
            model_name="evafinding",
            name="finding_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Deterministic key for cross-review deduplication: {check_id}_{ACCOUNT_CODE_OR_CATEGORY}.  Used to detect whether a previously-addressed finding should be skipped on re-review.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
