# Generated by Django 5.2.11 on 2026-03-11 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_populate_finding_keys"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="evafinding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("finding_key", ""), _negated=True),
                fields=("eva_review", "finding_key"),
                name="unique_finding_key_per_review",
            ),
        ),
    ]
