# Generated by Django 5.2.11 on 2026-03-11 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_fix_evaconversation_index_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FrankingAccountEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.CharField(max_length=255)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT_OF_TAX", "Payment of Tax"),
                            ("PAYG_INSTALMENT", "PAYG Instalment"),
                            ("REFUND_OF_TAX", "Refund of Income Tax"),
                            (
                                "FRANKING_DEBIT_DIVIDEND",
                                "Franking Debit — Dividend Paid",
                            ),
                            ("FRANKING_CREDIT_RECEIVED", "Franking Credit Received"),
                            ("OPENING_BALANCE", "Opening Balance"),
                            ("OTHER_CREDIT", "Other Credit"),
                            ("OTHER_DEBIT", "Other Debit"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="franking_entries",
                        to="core.entity",
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="franking_entries",
                        to="core.financialyear",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "sort_order", "created_at"],
            },
        ),
    ]
