# Generated by Django 5.2.11 on 2026-03-12 06:37
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_pgvector_embedding'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='knowledgechunk',
            name='knowledge_chunk_embedding_hnsw',
        ),
    ]
