# Generated by Django 5.2.11 on 2026-03-12 06:37
from django.db import migrations


def _is_postgres(schema_editor):
    return schema_editor.connection.vendor == "postgresql"


class SafeRemoveIndex(migrations.RemoveIndex):
    """RemoveIndex that is a no-op on non-PostgreSQL backends."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if _is_postgres(schema_editor):
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if _is_postgres(schema_editor):
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_pgvector_embedding'),
    ]

    operations = [
        SafeRemoveIndex(
            model_name='knowledgechunk',
            name='knowledge_chunk_embedding_hnsw',
        ),
    ]
