# Generated by Django 5.2.11 on 2026-03-13 03:07
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_remove_knowledgechunk_knowledge_chunk_embedding_hnsw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('bank_upload', 'Bank Statement Uploaded'),
                    ('classify_complete', 'AI Classification Complete'),
                    ('classify_started', 'AI Classification Started'),
                    ('tb_import', 'Trial Balance Imported'),
                    ('tb_dup_merged', 'TB Duplicate Accounts Merged'),
                    ('journal_posted', 'Journal Entry Posted'),
                    ('year_finalised', 'Financial Year Finalised'),
                    ('fy_status_changed', 'Financial Year Status Changed'),
                    ('audit_run', 'Audit Risk Analysis Run'),
                    ('review_approved', 'Transactions Approved'),
                    ('doc_generated', 'Document Generated'),
                    ('mgmt_accts_gen', 'Management Accounts Generated'),
                    ('eva_review_triggered', 'Eva Review Triggered'),
                    ('eva_review_cleared', 'Eva Review Cleared'),
                    ('eva_finding_addressed', 'Eva Finding Addressed'),
                    ('eva_clarification', 'Eva Clarification Submitted'),
                    ('bas_commentary_generated', 'BAS Commentary Generated'),
                    ('bas_commentary_edited', 'BAS Commentary Edited'),
                    ('bas_commentary_regenerated', 'BAS Commentary Regenerated'),
                    ('bas_commentary_sent', 'BAS Commentary Sent'),
                    ('bas_commentary_deleted', 'BAS Commentary Deleted'),
                    ('general', 'General'),
                ],
                default='general',
                max_length=40,
            ),
        ),
    ]
