# Generated by Django 5.2.11 on 2026-03-13 06:04
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_merge_0089_0090'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='engagementletter',
            new_name='core_engage_entity__9f9c36_idx',
            old_name='core_engage_entity__idx',
        ),
        migrations.AlterField(
            model_name='engagementletter',
            name='notes',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Internal notes about this engagement letter.',
            ),
        ),
    ]
