# Generated by Django 5.2.11 on 2026-03-16 00:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_rename_core_engage_entity__idx_core_engage_entity__9f9c36_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Crypto Portfolio', max_length=255)),
                ('exchange', models.CharField(default='Bybit', max_length=100)),
                ('base_currency', models.CharField(default='USDT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crypto Portfolio',
                'verbose_name_plural': 'Crypto Portfolios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CryptoPerformanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holdings_json', models.JSONField(blank=True, default=list)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('priced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='core.cryptoportfolio')),
            ],
            options={
                'verbose_name': 'Crypto Performance Snapshot',
                'verbose_name_plural': 'Crypto Performance Snapshots',
            },
        ),
        migrations.CreateModel(
            name='CryptoTradeImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file', models.FileField(upload_to='crypto_portfolio/imports/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=500)),
                ('exchange', models.CharField(default='Bybit', max_length=100)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crypto_trade_imports', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='core.cryptoportfolio')),
            ],
            options={
                'verbose_name': 'Crypto Trade Import',
                'verbose_name_plural': 'Crypto Trade Imports',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='CryptoTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spot_pair', models.CharField(max_length=50)),
                ('base_asset', models.CharField(max_length=20)),
                ('quote_asset', models.CharField(max_length=20)),
                ('order_type', models.CharField(blank=True, default='', max_length=50)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('fee_coin', models.CharField(blank=True, default='', max_length=20)),
                ('exec_fee', models.DecimalField(decimal_places=12, default=0, max_digits=24)),
                ('filled_value', models.DecimalField(decimal_places=12, default=0, max_digits=24)),
                ('filled_price', models.DecimalField(decimal_places=12, default=0, max_digits=24)),
                ('filled_quantity', models.DecimalField(decimal_places=12, default=0, max_digits=24)),
                ('transaction_id', models.CharField(max_length=100)),
                ('order_no', models.CharField(blank=True, default='', max_length=100)),
                ('executed_at', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.cryptoportfolio')),
                ('trade_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.cryptotradeimport')),
            ],
            options={
                'verbose_name': 'Crypto Trade',
                'verbose_name_plural': 'Crypto Trades',
                'ordering': ['executed_at', 'created_at'],
                'indexes': [models.Index(fields=['portfolio', 'executed_at'], name='core_crypto_portfol_85e960_idx'), models.Index(fields=['portfolio', 'base_asset'], name='core_crypto_portfol_23567a_idx'), models.Index(fields=['transaction_id'], name='core_crypto_transac_85e78a_idx')],
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'transaction_id'), name='uniq_crypto_trade_portfolio_txn')],
            },
        ),
    ]
