# Generated by Django 5.2.11 on 2026-03-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0092_rename_core_engage_entity__idx_core_engage_entity__9f9c36_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financialstatementtemplate",
            options={"ordering": ["entity_type", "document_type"]},
        ),
        migrations.AddField(
            model_name="financialstatementtemplate",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("COVER", "Cover Page"),
                    ("DETAILED_PL", "Detailed Profit and Loss"),
                    ("BALANCE_SHEET", "Balance Sheet"),
                    ("SUMMARY_PL", "Summary P&L"),
                    ("NOTES", "Notes to Financial Statements"),
                    ("DECLARATION", "Declaration"),
                    ("COMPILATION", "Compilation Report"),
                    ("DISTRIBUTION", "Distribution Summary"),
                ],
                default="COVER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="financialstatementtemplate",
            name="template_file",
            field=models.FileField(upload_to="fs_templates/"),
        ),
        migrations.AlterUniqueTogether(
            name="financialstatementtemplate",
            unique_together={("document_type", "entity_type", "is_active")},
        ),
    ]
