# Generated by Django 5.2.11 on 2026-03-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_firmsettings_extended_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='governingdocumentchunk',
            new_name='core_govern_entity__20bbbb_idx',
            old_name='core_govdocc_entity__7f0b6f_idx',
        ),
        migrations.RenameIndex(
            model_name='governingdocumentchunk',
            new_name='core_govern_governi_7a412e_idx',
            old_name='core_govdocc_govdoc__1c5356_idx',
        ),
    ]
