# Generated by Django 5.2.11 on 2026-03-18 13:42
# Safe version: uses RunPython to handle cases where the old indexes may
# already have been renamed, or where a previous failed migration left the
# server in an inconsistent state (e.g. vector→jsonb cast error on 0098).
from django.db import migrations, connection


def _index_exists(index_name):
    """Check if a named index exists in the PostgreSQL database."""
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_indexes WHERE indexname = %s",
            [index_name],
        )
        return cursor.fetchone() is not None


def rename_index_safe(old_name, new_name):
    """Rename an index only if old name exists and new name doesn't."""
    if _index_exists(old_name) and not _index_exists(new_name):
        with connection.cursor() as cursor:
            cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')


def rename_indexes_forward(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    rename_index_safe(
        "core_govdocc_entity__7f0b6f_idx",
        "core_govern_entity__20bbbb_idx",
    )
    rename_index_safe(
        "core_govdocc_govdoc__1c5356_idx",
        "core_govern_governi_7a412e_idx",
    )


def rename_indexes_backward(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    rename_index_safe(
        "core_govern_entity__20bbbb_idx",
        "core_govdocc_entity__7f0b6f_idx",
    )
    rename_index_safe(
        "core_govern_governi_7a412e_idx",
        "core_govdocc_govdoc__1c5356_idx",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_firmsettings_extended_fields'),
    ]

    operations = [
        migrations.RunPython(rename_indexes_forward, rename_indexes_backward),
    ]
