# Generated by Django 5.2.11 on 2026-03-18 12:18

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_firmsettings_extended_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgechunk',
            name='embedding_vector',
            field=core.models.VectorField(blank=True, default=list, dimensions=1536, help_text='pgvector embedding for native cosine distance search', null=True),
        ),
    ]
