# Generated by Django 5.2.11 on 2026-03-19 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_alter_knowledgechunk_embedding_vector'),
        ('core', '0098_rename_core_govdocc_entity__7f0b6f_idx_core_govern_entity__20bbbb_idx_and_more'),
    ]

    operations = [
    ]
