# Generated by Django 5.2.11 on 2026-03-19 01:06

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_merge_20260319_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgechunk',
            name='embedding_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='pgvector embedding for native cosine distance search', null=True),
        ),
    ]
