# Generated by Django 5.2.11 on 2026-03-19 06:18
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_merge_0100_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearendcommentary',
            name='financial_year',
            field=models.OneToOneField(
                help_text='One commentary per financial year (upsert on regenerate).',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='year_end_commentary',
                to='core.financialyear',
            ),
        ),
    ]
