# Generated by Django 5.2.11 on 2026-03-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_alter_yearendcommentary_financial_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='section',
            field=models.CharField(choices=[('suspense', 'Suspense'), ('revenue', 'Revenue'), ('cost_of_sales', 'Cost of Sales'), ('expenses', 'Expenses'), ('current_assets', 'Current Assets'), ('non_current_assets', 'Non-Current Assets'), ('assets', 'Assets'), ('current_liabilities', 'Current Liabilities'), ('non_current_liabilities', 'Non-Current Liabilities'), ('liabilities', 'Liabilities'), ('equity', 'Equity'), ('capital_accounts', 'Capital Accounts'), ('pl_appropriation', 'P&L Appropriation')], help_text='Which section of the financial statements this belongs to', max_length=30),
        ),
        migrations.AlterField(
            model_name='entitychartofaccount',
            name='section',
            field=models.CharField(choices=[('suspense', 'Suspense'), ('revenue', 'Revenue'), ('cost_of_sales', 'Cost of Sales'), ('expenses', 'Expenses'), ('current_assets', 'Current Assets'), ('non_current_assets', 'Non-Current Assets'), ('assets', 'Assets'), ('current_liabilities', 'Current Liabilities'), ('non_current_liabilities', 'Non-Current Liabilities'), ('liabilities', 'Liabilities'), ('equity', 'Equity'), ('capital_accounts', 'Capital Accounts'), ('pl_appropriation', 'P&L Appropriation')], help_text='Which section of the financial statements this belongs to', max_length=30),
        ),
    ]
