# Generated by Django 5.2.11 on 2026-03-24 00:14
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_alter_chartofaccount_section_and_more'),
        ('core', '0103_regenerate_summary_pl_template'),
    ]

    operations = [
    ]
