# Generated by Django 5.2.11 on 2026-03-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_stagedimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityofficer',
            name='role',
            field=models.CharField(choices=[('director', 'Director'), ('partner', 'Partner'), ('trustee', 'Trustee'), ('beneficiary', 'Beneficiary'), ('secretary', 'Secretary'), ('public_officer', 'Public Officer'), ('sole_trader', 'Sole Trader / Proprietor'), ('chairperson', 'Chairperson'), ('unit_holder', 'Unit Holder')], max_length=20),
        ),
    ]
