# Generated by Django 5.2.11 on 2026-03-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_alter_entityofficer_role'),
        ('core', '0111_seed_capital_account_templates'),
    ]

    operations = [
    ]
