# Generated by Django 5.2.11 on 2026-04-10 07:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0112_merge_20260327_1704"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountRangeAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("trust", "Trust"),
                            ("partnership", "Partnership"),
                            ("sole_trader", "Sole Trader"),
                            ("smsf", "SMSF"),
                        ],
                        help_text="Entity type this alias applies to",
                        max_length=20,
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        help_text='Alias key, e.g. "RevAll", "ExpSalaryWages"',
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text='Human-readable description, e.g. "Revenue"',
                        max_length=255,
                    ),
                ),
                (
                    "dc_sign",
                    models.CharField(
                        choices=[("D", "Debit"), ("C", "Credit")],
                        help_text="Natural sign of the range — Debit or Credit",
                        max_length=1,
                    ),
                ),
                (
                    "range_from",
                    models.CharField(
                        help_text='First account code in the range, e.g. "0001"',
                        max_length=10,
                    ),
                ),
                (
                    "range_to",
                    models.CharField(
                        help_text="Last account code in the range (inclusive)",
                        max_length=10,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Grouping label, e.g. "Revenue", "Current Assets"',
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["entity_type", "range_from", "alias"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "range_from", "range_to"],
                        name="core_accoun_entity__f818fb_idx",
                    )
                ],
                "unique_together": {("entity_type", "alias")},
            },
        ),
    ]
