# Generated by Django 5.2.11 on 2026-04-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_rdti_drafter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdtiapplication',
            name='aggregated_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Aggregated turnover for the income year (determines refundable vs non-refundable offset)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='rdtiapplication',
            name='anzsic_code',
            field=models.CharField(blank=True, help_text='Full 4-digit ANZSIC code', max_length=10),
        ),
        migrations.AlterField(
            model_name='rdtiapplication',
            name='anzsic_division',
            field=models.CharField(blank=True, choices=[('A', 'A — Agriculture, Forestry and Fishing'), ('B', 'B — Mining'), ('C', 'C — Manufacturing'), ('D', 'D — Electricity, Gas, Water and Waste Services'), ('E', 'E — Construction'), ('F', 'F — Wholesale Trade'), ('G', 'G — Retail Trade'), ('H', 'H — Accommodation and Food Services'), ('I', 'I — Transport, Postal and Warehousing'), ('J', 'J — Information Media and Telecommunications'), ('K', 'K — Financial and Insurance Services'), ('L', 'L — Rental, Hiring and Real Estate Services'), ('M', 'M — Professional, Scientific and Technical Services'), ('N', 'N — Administrative and Support Services'), ('O', 'O — Public Administration and Safety'), ('P', 'P — Education and Training'), ('Q', 'Q — Health Care and Social Assistance'), ('R', 'R — Arts and Recreation Services'), ('S', 'S — Other Services')], max_length=2, verbose_name='ANZSIC Division'),
        ),
        migrations.AlterField(
            model_name='rdtiapplication',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of employees (FTE) during the R&D period', null=True),
        ),
        migrations.AlterField(
            model_name='rdtiapplication',
            name='entity_bears_financial_burden',
            field=models.BooleanField(blank=True, help_text='The R&D entity bears the financial burden of the R&D activities', null=True),
        ),
        migrations.AlterField(
            model_name='rdtiapplication',
            name='entity_controls_activities',
            field=models.BooleanField(blank=True, help_text='The R&D entity controls the R&D activities', null=True),
        ),
        migrations.AlterField(
            model_name='rdtiapplication',
            name='ip_owned_by_entity',
            field=models.BooleanField(blank=True, help_text='IP arising from R&D is owned by the R&D entity', null=True),
        ),
        migrations.AlterField(
            model_name='rdtiapplication',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal consultant notes'),
        ),
        migrations.AlterField(
            model_name='rdticoreactivity',
            name='competent_professional',
            field=models.TextField(blank=True, help_text='Why a competent professional could not have known or determined the outcome (4,000 char limit)'),
        ),
        migrations.AlterField(
            model_name='rdticoreactivity',
            name='conclusions',
            field=models.TextField(blank=True, help_text="Conclusions — findings including what didn't work (4,000 char limit)"),
        ),
        migrations.AlterField(
            model_name='rdticoreactivity',
            name='description',
            field=models.TextField(blank=True, help_text='Description of core R&D activity (4,000 char limit)'),
        ),
        migrations.AlterField(
            model_name='rdticoreactivity',
            name='draft_complete',
            field=models.BooleanField(default=False, help_text='All 8 narrative fields have been drafted and are within character limits'),
        ),
        migrations.AlterField(
            model_name='rdticoreactivity',
            name='evaluation_method',
            field=models.TextField(blank=True, help_text='Evaluation method — metrics and criteria (4,000 char limit)'),
        ),
        migrations.AlterField(
            model_name='rdticoreactivity',
            name='evidence_kept',
            field=models.JSONField(blank=True, default=list, help_text='List of evidence types kept for this activity'),
        ),
        migrations.AlterField(
            model_name='rdticoreactivity',
            name='experiment',
            field=models.TextField(blank=True, help_text='Experiment and how it tested the hypothesis (4,000 char limit)'),
        ),
        migrations.AlterField(
            model_name='rdticoreactivity',
            name='hypothesis',
            field=models.TextField(blank=True, help_text='Hypothesis (overarching + sub-hypotheses) (4,000 char limit)'),
        ),
        migrations.AlterField(
            model_name='rdticoreactivity',
            name='new_knowledge',
            field=models.TextField(blank=True, help_text='New knowledge produced — domain-level, not project-level (4,000 char limit)'),
        ),
        migrations.AlterField(
            model_name='rdticoreactivity',
            name='outcome_not_known_in_advance',
            field=models.TextField(blank=True, help_text='How the company determined the outcome could not be known in advance — sources investigated (4,000 char limit)'),
        ),
        migrations.AlterField(
            model_name='rdticoreactivity',
            name='sources_investigated',
            field=models.JSONField(blank=True, default=list, help_text='List of sources investigated before commencing the activity'),
        ),
        migrations.AlterField(
            model_name='rdtidraftversion',
            name='field_name',
            field=models.CharField(help_text="Name of the narrative field (e.g. 'hypothesis', 'new_knowledge')", max_length=100),
        ),
        migrations.AlterField(
            model_name='rdtidraftversion',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Whether this is the currently active version for this field'),
        ),
        migrations.AlterField(
            model_name='rdtidraftversion',
            name='prompt_version',
            field=models.CharField(blank=True, help_text='Version identifier of the prompt used to generate this draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='rdtidraftversion',
            name='target_id',
            field=models.UUIDField(help_text='UUID of the target object'),
        ),
        migrations.AlterField(
            model_name='rdtiexpenditureyear',
            name='financial_year_label',
            field=models.CharField(help_text='e.g. FY2025', max_length=20),
        ),
        migrations.AlterField(
            model_name='rdtiflag',
            name='flag_type',
            field=models.CharField(choices=[('hypothesis_objective', 'Hypothesis reads as objective'), ('hypothesis_no_measurable', 'Hypothesis has no measurable outcome'), ('experiment_no_hypothesis', "Experiment doesn't reference hypothesis"), ('new_knowledge_project', 'New knowledge describes project delivery, not domain knowledge'), ('excluded_category', 'Activity description includes excluded-category language'), ('over_char_limit', 'Field exceeds 4,000 character limit'), ('missing_mandatory', 'Missing mandatory structured field'), ('hypothesis_no_substructure', 'Hypothesis lacks sub-structure for complex activity'), ('competent_prof_generic', 'Competent professional section lacks specific technical detail'), ('sources_generic', 'Sources investigated section is generic'), ('conclusions_no_failures', "Conclusions don't mention what didn't work"), ('evaluation_no_quantitative', 'Evaluation method lacks quantitative criteria'), ('cross_field_inconsistency', 'Cross-field inconsistency detected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rdtiflag',
            name='message',
            field=models.TextField(help_text='Human-readable explanation of the flag'),
        ),
        migrations.AlterField(
            model_name='rdtiflag',
            name='suggestion',
            field=models.TextField(blank=True, help_text='Suggested fix or improvement'),
        ),
        migrations.AlterField(
            model_name='rdtiproject',
            name='anzsrc_code',
            field=models.CharField(blank=True, help_text='Full 6-digit ANZSRC code', max_length=10),
        ),
        migrations.AlterField(
            model_name='rdtiproject',
            name='anzsrc_division',
            field=models.CharField(blank=True, choices=[('01', '01 — Mathematical Sciences'), ('02', '02 — Physical Sciences'), ('03', '03 — Chemical Sciences'), ('04', '04 — Earth Sciences'), ('05', '05 — Environmental Sciences'), ('06', '06 — Biological Sciences'), ('07', '07 — Agricultural and Veterinary Sciences'), ('08', '08 — Information and Computing Sciences'), ('09', '09 — Engineering'), ('10', '10 — Technology'), ('11', '11 — Medical and Health Sciences'), ('12', '12 — Built Environment and Design'), ('13', '13 — Education'), ('14', '14 — Economics'), ('15', '15 — Commerce, Management, Tourism and Services'), ('16', '16 — Studies in Human Society'), ('17', '17 — Psychology and Cognitive Sciences'), ('18', '18 — Law and Legal Studies'), ('19', '19 — Studies in Creative Arts and Writing'), ('20', '20 — Language, Communication and Culture'), ('21', '21 — History and Archaeology'), ('22', '22 — Philosophy and Religious Studies')], max_length=2, verbose_name='ANZSRC Division (Field of Research)'),
        ),
        migrations.AlterField(
            model_name='rdtiproject',
            name='beneficiary_description',
            field=models.TextField(blank=True, help_text='Beneficiary description: IP ownership, control, financial burden (4,000 char limit)'),
        ),
        migrations.AlterField(
            model_name='rdtiproject',
            name='documents_kept',
            field=models.TextField(blank=True, help_text='Documents kept to demonstrate R&D activities (4,000 char limit)'),
        ),
        migrations.AlterField(
            model_name='rdtiproject',
            name='objectives',
            field=models.TextField(blank=True, help_text='Project objectives (AusIndustry field, 4,000 char limit)'),
        ),
        migrations.AlterField(
            model_name='rdtiproject',
            name='plant_and_facilities',
            field=models.TextField(blank=True, help_text='Plant and facilities used in the R&D activities (4,000 char limit)'),
        ),
        migrations.AlterField(
            model_name='rdtiproject',
            name='project_end_date',
            field=models.DateField(blank=True, help_text='Expected end date (may be in a future FY)', null=True),
        ),
        migrations.AlterField(
            model_name='rdtisupportingactivity',
            name='description',
            field=models.TextField(blank=True, help_text='Description of supporting activity (4,000 char limit)'),
        ),
        migrations.AlterField(
            model_name='rdtisupportingactivity',
            name='direct_relation',
            field=models.TextField(blank=True, help_text='How this activity directly relates to the core activity (4,000 char limit)'),
        ),
    ]
