# Generated by Django 5.2.11 on 2026-04-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0120_entity_include_comparative_figures"),
    ]

    operations = [
        migrations.AddField(
            model_name="governingdocument",
            name="extraction_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Error message from the most recent failed extraction attempt",
            ),
        ),
        migrations.AddField(
            model_name="governingdocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="governingdocument",
            name="extraction_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("completed_with_warnings", "Completed with Warnings"),
                    ("ocr_pending", "OCR Pending"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
