# Generated by Django 5.2.13 on 2026-04-29 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_officer_distribution_history_cascade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStyleProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('style_descriptor', models.TextField(blank=True, help_text="Human-readable summary of this accountant's writing style (for admin review).")),
                ('prompt_fragment', models.TextField(blank=True, help_text="Concise style instructions injected into Eva's system prompt when generating documents for this user.")),
                ('bas_commentary_edits_analysed', models.IntegerField(default=0, help_text='Number of BAS commentary edits used to build this profile.')),
                ('yearend_commentary_edits_analysed', models.IntegerField(default=0, help_text='Number of year-end commentary edits used to build this profile.')),
                ('confidence_score', models.FloatField(default=0.0, help_text='0.0-1.0 confidence in this profile. Low confidence profiles are not injected.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eva_style_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Style Profile',
                'verbose_name_plural': 'User Style Profiles',
            },
        ),
        migrations.CreateModel(
            name='EvaAgentTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('chat', 'Chat Message'), ('finalisation', 'Finalisation Gate'), ('proactive', 'Proactive Scan'), ('commentary', 'Commentary Generation')], default='chat', max_length=20)),
                ('trigger_input', models.TextField(blank=True, help_text='The original user message or system trigger that started this agent run.')),
                ('steps', models.JSONField(default=list, help_text='Ordered list of {step, tool_name, tool_args, tool_result, reasoning} dicts.')),
                ('total_iterations', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('final_answer', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_traces', to='core.financialyear')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eva_agent_traces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eva Agent Trace',
                'verbose_name_plural': 'Eva Agent Traces',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['financial_year', 'trigger_type'], name='core_evaage_financi_3f8a4a_idx'), models.Index(fields=['user', 'created_at'], name='core_evaage_user_id_f20049_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvaCommentaryEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('bas_commentary', 'BAS Commentary'), ('yearend_commentary', 'Year-End Commentary'), ('client_summary', 'Client Summary')], max_length=30)),
                ('source_document_id', models.CharField(help_text='UUID of the BASPeriodCommentary or YearEndCommentary that was edited.', max_length=100)),
                ('section_name', models.CharField(blank=True, help_text="Which section was edited (e.g. 'section_revenue', 'section_snapshot').", max_length=100)),
                ('original_text', models.TextField(help_text='AI-generated text before editing.')),
                ('edited_text', models.TextField(help_text='Final text after accountant edits.')),
                ('diff_summary', models.TextField(blank=True, help_text='LLM-generated plain-English summary of what changed and why.')),
                ('char_delta', models.IntegerField(default=0, help_text='Character count change (edited - original). Negative = shortened.')),
                ('processed_for_style', models.BooleanField(default=False, help_text='Whether this edit has been consumed by the style learning engine.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentary_edits', to='core.entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentary_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eva Commentary Edit',
                'verbose_name_plural': 'Eva Commentary Edits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'document_type', 'processed_for_style'], name='core_evacom_user_id_43e1c1_idx'), models.Index(fields=['entity', 'document_type'], name='core_evacom_entity__0d2697_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvaLearnedLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_text', models.TextField(help_text='Plain-English lesson extracted by Claude Sonnet during reflection.')),
                ('embedding_vector', models.JSONField(blank=True, help_text='1536-dim float list from text-embedding-3-small.', null=True)),
                ('category', models.CharField(choices=[('classification', 'Account Classification'), ('compliance', 'Compliance Preference'), ('style', 'Communication Style'), ('workflow', 'Workflow Preference'), ('entity_specific', 'Entity-Specific Rule'), ('general', 'General Practice Rule')], default='general', max_length=30)),
                ('priority_weight', models.FloatField(default=1.5, help_text='Multiplier applied to similarity score during retrieval. >1 boosts this lesson above standard KB chunks.')),
                ('source_signal_type', models.CharField(blank=True, help_text="The signal that generated this lesson (e.g. 'EvaClarification', 'EvaFindingSuppression').", max_length=50)),
                ('source_signal_id', models.CharField(blank=True, help_text='PK of the source signal record.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive lessons are excluded from retrieval.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_entity', models.ForeignKey(blank=True, help_text='The entity this lesson applies to (null = all entities).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learned_lessons', to='core.entity')),
                ('source_user', models.ForeignKey(blank=True, help_text='The accountant whose behaviour generated this lesson (null = firm-wide).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eva Learned Lesson',
                'verbose_name_plural': 'Eva Learned Lessons',
                'ordering': ['-priority_weight', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='core_evalea_categor_d2d0ef_idx'), models.Index(fields=['source_user', 'is_active'], name='core_evalea_source__933876_idx'), models.Index(fields=['source_entity', 'is_active'], name='core_evalea_source__6c9c14_idx')],
            },
        ),
    ]
