# Generated by Django 5.2.11 on 2026-04-30 06:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_userstyleprofile_evaagenttrace_evacommentaryedit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAccountMappingHint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('company', 'Company'), ('trust', 'Trust'), ('partnership', 'Partnership'), ('sole_trader', 'Sole Trader'), ('smsf', 'SMSF')], help_text='Entity type this hint applies to', max_length=20)),
                ('account_code', models.CharField(help_text="Source account code (e.g. '200', '610')", max_length=20)),
                ('account_name', models.CharField(blank=True, default='', help_text='Most recently seen account name for this code', max_length=255)),
                ('confidence', models.PositiveIntegerField(default=1, help_text='Number of times confirmed across different entities')),
                ('last_confirmed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapped_line_item', models.ForeignKey(help_text='The AccountMapping line this code should map to', on_delete=django.db.models.deletion.CASCADE, related_name='global_hints', to='core.accountmapping')),
            ],
            options={
                'ordering': ['-confidence', 'entity_type', 'account_code'],
                'indexes': [models.Index(fields=['entity_type', 'account_code'], name='core_global_entity__2a528e_idx')],
                'unique_together': {('entity_type', 'account_code')},
            },
        ),
    ]
