# Generated by Django 5.2.11 on 2026-05-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0126_userstyleprofile_evaagenttrace_evacommentaryedit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgedocument",
            name="category",
            field=models.CharField(
                choices=[
                    ("firm_procedures", "Firm Procedures"),
                    ("firm_technical", "Firm Technical Positions"),
                    ("firm_training", "Firm Training"),
                    ("firm_precedents", "Firm Precedents"),
                    ("ato_rulings", "ATO Rulings"),
                    ("ato_statements", "ATO Practice Statements"),
                    ("ato_alerts", "ATO Alerts"),
                    ("ato_benchmarks", "ATO Benchmarks"),
                    ("legislation", "Legislation"),
                    ("aasb_standards", "AASB Standards"),
                    ("cpa_materials", "CPA Materials"),
                    ("ca_anz_materials", "CA ANZ Materials"),
                    ("treasury", "Treasury"),
                    ("apes_standards", "APES Standards"),
                    ("tpb_guidance", "TPB Guidance"),
                    ("case_law", "Case Law"),
                    ("industry_guides", "Industry Guides"),
                    ("client_precedents", "Client Precedents"),
                    ("ifrs_references", "IFRS References"),
                    ("interpretations", "Accounting Interpretations"),
                    ("income_tax", "Income Tax"),
                    ("gst_bas", "GST & BAS"),
                    ("fbt", "Fringe Benefits Tax"),
                    ("superannuation", "Superannuation"),
                    ("firm_engagement", "Firm — Engagement Letters"),
                    ("firm_checklists", "Firm — Review Checklists"),
                    ("firm_quality", "Firm — Quality Control"),
                    ("firm_style", "Firm — Style Guides"),
                    ("disclosure_companies", "Disclosure — Companies"),
                    ("disclosure_trusts", "Disclosure — Trusts"),
                    ("disclosure_smsf", "Disclosure — SMSF"),
                    ("disclosure_partnerships", "Disclosure — Partnerships"),
                    ("disclosure_sole_traders", "Disclosure — Sole Traders"),
                    ("industry_construction", "Industry — Construction"),
                    ("industry_medical", "Industry — Medical"),
                    ("industry_hospitality", "Industry — Hospitality"),
                    ("industry_professional", "Industry — Professional Services"),
                    ("industry_retail", "Industry — Retail"),
                    ("industry_nfp", "Industry — Not For Profit"),
                    ("training_eva", "Training — Eva User Guide"),
                    ("training_statementhub", "Training — StatementHub Procedures"),
                    ("training_onboarding", "Training — Onboarding"),
                    ("industry_benchmarks", "Industry Benchmarks"),
                    ("financial_ratios", "Financial Ratios"),
                    ("other", "Other"),
                ],
                default="firm_procedures",
                max_length=30,
            ),
        ),
    ]
