# Generated by Django 5.2.11 on 2026-05-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_generalpool_generalpoolasset_generalpooldisp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpool',
            name='assessable_income_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount added to assessable income when disposal proceeds cause pool to go negative (s 328-215).', max_digits=15),
        ),
        migrations.AlterField(
            model_name='generalpool',
            name='iawo_threshold',
            field=models.DecimalField(decimal_places=2, default=20000, help_text='Instant asset write-off limit for this income year. Defaults to $20,000.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='generalpool',
            name='low_pool_writeoff',
            field=models.BooleanField(default=False, help_text='True when Subtotal E < IAWO threshold - entire balance written off.'),
        ),
        migrations.AlterField(
            model_name='generalpool',
            name='opening_pool_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Closing pool balance from the prior income year (Step 1).', max_digits=15),
        ),
        migrations.AlterField(
            model_name='generalpoolasset',
            name='business_use_pct',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Percentage used for business / taxable purposes (0-100).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='generalpoolasset',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Full cost (exclude GST if registered). For cars, cap at car cost limit.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='generalpoolasset',
            name='is_improvement',
            field=models.BooleanField(default=False, help_text='True if this is a cost addition / improvement to an existing pooled asset.'),
        ),
        migrations.AlterField(
            model_name='generalpooldisposal',
            name='termination_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount received (sale price, insurance, trade-in). Exclude GST if registered.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='trialbalanceline',
            name='source',
            field=models.CharField(blank=True, choices=[('tb_import', 'Trial Balance Import'), ('bank_statement', 'Bank Statement'), ('manual_journal', 'Manual Journal'), ('journal_upload', 'Journal Upload'), ('rollover', 'Rolled Forward'), ('general_pool', 'General Pool Depreciation')], default='tb_import', help_text='Where this line originated from', max_length=20),
        ),
    ]
