# Generated by Django 5.2.11 on 2026-05-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_increase_account_code_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_code',
            field=models.CharField(help_text='Account code, e.g. "500", "1510", "2000.01"', max_length=50),
        ),
    ]
