# Generated by Django 5.2.11 on 2026-05-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_widen_entity_coa_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitychartofaccount',
            name='account_code',
            field=models.CharField(help_text='Account code, e.g. "500", "1510", "2000.01"', max_length=50),
        ),
    ]
