# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_widen_entity_coa_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccountmapping',
            name='client_account_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientaccountmapping',
            name='target_entity_account',
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    'StatementHub COA account this source code maps to. '
                    'Set by the import wizard; pre-fills entity_acct_code on '
                    'subsequent imports.'
                ),
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name='client_account_mappings',
                to='core.entitychartofaccount',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='clientaccountmapping',
            unique_together={('entity', 'client_account_code', 'client_account_name')},
        ),
        migrations.AlterModelOptions(
            name='clientaccountmapping',
            options={'ordering': ['client_account_code', 'client_account_name']},
        ),
    ]
