# Generated by Django 5.2.11 on 2026-06-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_adjustingjournal_trust_distribution_void'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustingjournal',
            name='journal_type',
            field=models.CharField(choices=[('general', 'General Journal'), ('adjusting', 'Adjusting Entry'), ('year_end', 'Year-End Entry'), ('depreciation', 'Depreciation Entry'), ('dep_reversal', 'Depreciation Reversal'), ('tax', 'Tax Adjustment'), ('tax_provision', 'Tax Provision')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='trialbalanceline',
            name='source',
            field=models.CharField(blank=True, choices=[('tb_import', 'Trial Balance Import'), ('bank_statement', 'Bank Statement'), ('manual_journal', 'Manual Journal'), ('journal_upload', 'Journal Upload'), ('rollover', 'Rolled Forward'), ('general_pool', 'General Pool Depreciation'), ('depreciation_schedule', 'Depreciation Schedule Posting'), ('depreciation_reversal', 'Depreciation Schedule Reversal')], default='tb_import', help_text='Where this line originated from', max_length=30),
        ),
    ]
