# Generated by Django 5.2.11 on 2026-07-09 00:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_fy2025_stage3_tax_rates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocumenttemplate',
            name='document_type',
            field=models.CharField(choices=[('div7a_loan_agreement', 'Div 7A Loan Agreement'), ('trust_deed_change_trustee', 'Trust Deed — Change Trustee'), ('trust_deed_add_beneficiary', 'Trust Deed — Add Beneficiary'), ('trust_deed_remove_beneficiary', 'Trust Deed — Remove Beneficiary'), ('trust_deed_extend_vesting', 'Trust Deed — Extend Vesting'), ('trust_deed_update_distribution', 'Trust Deed — Update Distribution'), ('company_constitution', 'Company Constitution'), ('company_constitution_special', 'Company Constitution — Special Purpose'), ('company_establishment', 'Company Establishment Package'), ('discretionary_trust_deed', 'Discretionary Trust Deed'), ('unit_trust_deed', 'Unit Trust Deed'), ('unit_trust_deed_ancillaries', 'Unit Trust Deed — Ancillary Documents'), ('unit_transfer', 'Unit Transfer Package'), ('partnership_agreement', 'Partnership Agreement'), ('dividend_statement', 'Dividend Statement'), ('dividend_minutes', 'Dividend Declaration Minutes'), ('solvency_resolution', 'Solvency Resolution'), ('directors_declaration', "Director's Declaration"), ('directors_declaration_large', "Director's Declaration — Large Proprietary"), ('directors_declaration_gp', "Director's Declaration — General Purpose"), ('directors_report', "Director's Report"), ('shareholder_loan_ack', 'Shareholder Loan Acknowledgment'), ('partner_statement', 'Partner Statement'), ('partnership_tax_summary', 'Partnership Tax Summary'), ('engagement_letter', 'Client Engagement Letter'), ('management_rep_letter', 'Management Representation Letter'), ('management_rep_letter_trust', 'Management Representation Letter — Trust'), ('management_rep_letter_partnership', 'Management Representation Letter — Partnership'), ('client_cover_letter', 'Client Cover Letter'), ('distribution_minutes', 'Trust Distribution Minutes'), ('section_100a_summary', 'Section 100A Summary')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='legaldocumenttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document_type',), name='unique_active_legal_template_per_type'),
        ),
    ]
