# Generated by Django 5.2.11 on 2026-08-17 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_alter_legaldocumenttemplate_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basperiod',
            name='amended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basperiod',
            name='amended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amended_bas_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basperiod',
            name='amended_since_lodgement',
            field=models.BooleanField(default=False, help_text='A transaction in this period changed after it was lodged'),
        ),
    ]
