# Generated by Django 5.2.11 on 2026-08-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_basperiod_amended_since_lodgement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='xpm_client_id',
            field=models.CharField(blank=True, db_index=True, help_text="Xero Practice Manager client reference. Job Tracker's Client.xpmId and CoWorker's entities.xpm_client_id hold the same value — this is the canonical key the three systems agree on. Deliberately NOT unique: one XPM client may own several entities here.", max_length=100, verbose_name='XPM Client ID'),
        ),
    ]
