# Generated by Django 5.2.11 on 2026-08-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_entity_xpm_client_id_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='jt_identity_cache',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entity',
            name='jt_identity_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
