# Generated by Django 5.2.11 on 2026-08-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_entity_jt_identity_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='identity_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
