# Generated by Django 5.2.11 on 2026-08-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_generateddocument_identity_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustingjournal',
            name='journal_type',
            field=models.CharField(choices=[('general', 'General Journal'), ('adjusting', 'Adjusting Entry'), ('year_end', 'Year-End Entry'), ('depreciation', 'Depreciation Entry'), ('dep_reversal', 'Depreciation Reversal'), ('tax', 'Tax Adjustment'), ('tax_reversal', 'Tax Reversal'), ('tax_provision', 'Tax Provision')], default='general', max_length=20),
        ),
    ]
