# Generated by Django 5.2.11 on 2026-08-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_alter_adjustingjournal_journal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='evafindingsuppression',
            name='amount_at_suppression',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Balance behind the finding when it was accepted. The suppression lapses once the balance moves materially, so accepting an exposure at one figure does not silence it at another. Null on rows created before this was recorded — those keep suppressing.', max_digits=15, null=True),
        ),
    ]
