# Generated by Django 5.2.11 on 2026-08-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_trust_4199_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrangealias',
            name='entity_type',
            field=models.CharField(choices=[('company', 'Company'), ('trust', 'Trust'), ('trust_unit', 'Unit Trust'), ('partnership', 'Partnership'), ('sole_trader', 'Sole Trader'), ('smsf', 'SMSF')], help_text='Entity type this alias applies to', max_length=20),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='entity_type',
            field=models.CharField(choices=[('company', 'Company'), ('trust', 'Trust'), ('trust_unit', 'Unit Trust'), ('partnership', 'Partnership'), ('sole_trader', 'Sole Trader'), ('smsf', 'SMSF')], help_text='Which entity type this account belongs to', max_length=20),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('trust', 'Trust'), ('trust_unit', 'Unit Trust'), ('partnership', 'Partnership'), ('sole_trader', 'Sole Trader'), ('smsf', 'SMSF')], help_text='Restrict to a specific entity type, or leave blank for all.', max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('company', 'Company'), ('trust', 'Trust'), ('trust_unit', 'Unit Trust'), ('partnership', 'Partnership'), ('sole_trader', 'Sole Trader'), ('smsf', 'SMSF')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialstatementtemplate',
            name='entity_type',
            field=models.CharField(choices=[('company', 'Company'), ('trust', 'Trust'), ('trust_unit', 'Unit Trust'), ('partnership', 'Partnership'), ('sole_trader', 'Sole Trader'), ('smsf', 'SMSF')], max_length=20),
        ),
        migrations.AlterField(
            model_name='globalaccountmappinghint',
            name='entity_type',
            field=models.CharField(choices=[('company', 'Company'), ('trust', 'Trust'), ('trust_unit', 'Unit Trust'), ('partnership', 'Partnership'), ('sole_trader', 'Sole Trader'), ('smsf', 'SMSF')], help_text='Entity type this hint applies to', max_length=20),
        ),
    ]
