# Generated by Django 5.2.11 on 2026-08-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_add_trust_unit_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityofficer',
            name='units_held',
            field=models.PositiveIntegerField(blank=True, help_text='Units held in a unit trust. The register is authoritative: distribution_percentage is derived from this, not typed.', null=True),
        ),
    ]
