# Generated by Django 5.2.11 on 2026-08-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_minli_to_trust_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST on this line. Authoritative: the BAS reports 1A/1B from the sum of these, not from G8/11. The gross the accountant keyed is reconstructed as (debit or credit) + gst_amount, which is what makes the split idempotent.', max_digits=15),
        ),
        migrations.AddField(
            model_name='journalline',
            name='is_gst_control',
            field=models.BooleanField(default=False, help_text="True for the two 3380 lines generated by the cashbook split. A structural flag rather than matching on account_code, so an accountant's own 3380 line (the quarterly ATO payment, say) is not wiped when the split regenerates."),
        ),
        migrations.AddField(
            model_name='journalline',
            name='tax_code',
            field=models.CharField(blank=True, default='', help_text="MYOB-style GST treatment for this line (GST, INP, FRE, CAP, N-T, ...). Same vocabulary as ChartOfAccount.tax_code. Blank means fall back to the account's chart default.", max_length=10),
        ),
        migrations.AlterField(
            model_name='adjustingjournal',
            name='journal_type',
            field=models.CharField(choices=[('general', 'General Journal'), ('cashbook', 'Cashbook (Cash Basis)'), ('adjusting', 'Adjusting Entry'), ('year_end', 'Year-End Entry'), ('depreciation', 'Depreciation Entry'), ('dep_reversal', 'Depreciation Reversal'), ('tax', 'Tax Adjustment'), ('tax_reversal', 'Tax Reversal'), ('tax_provision', 'Tax Provision')], default='general', max_length=20),
        ),
    ]
