# Generated by Django 5.2.11 on 2026-08-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_cashbook_gst_journal_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='gst_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The GST figure the accountant typed, when they overrode the calculated 1/11th (a partial input tax credit). Kept separate from gst_amount so that field stays purely derived: gst_amount doing double duty as both the input and the output made the reconstructed gross (debit + gst_amount) double-count on a first split. NULL means 'calculate it', which is a different answer from a deliberate 0.00.", max_digits=15, null=True),
        ),
    ]
