# Generated by Django 5.2.11 on 2026-09-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_alter_activitylog_event_type'),
        ('core', '0153_journalline_gst_override'),
    ]

    operations = [
    ]
