# Generated by Django 5.2.11 on 2026-09-01 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_merge_cashbook_gst_and_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustingjournal',
            name='reverses',
            field=models.ForeignKey(blank=True, help_text='The journal this one reverses. Set when a distribution is un-posted in a finalised year, where the original must stay posted on the audit trail. Without the link the two are only connected by description text, and anything reading the ledger sees the distribution but not its reversal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='core.adjustingjournal'),
        ),
    ]
