# Generated by Django 5.2.11 on 2026-09-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_adjustingjournal_reverses'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxplanningworksheet',
            name='income_before_recoupment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Net profit after tax adjustments, before recouping losses', max_digits=15),
        ),
        migrations.AddField(
            model_name='taxplanningworksheet',
            name='losses_carried_forward',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Losses remaining after recoupment, carried to the next year', max_digits=15),
        ),
        migrations.AddField(
            model_name='taxplanningworksheet',
            name='losses_recouped',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Carried-forward losses absorbed by this year's income", max_digits=15),
        ),
        migrations.AddField(
            model_name='taxplanningworksheet',
            name='undistributed_brought_forward',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Credit balance in 4199 brought forward — itself distributable', max_digits=15),
        ),
    ]
