# Generated by Django 5.2.11 on 2026-09-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_taxplanningworksheet_income_before_recoupment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='include_comparative_figures',
            field=models.BooleanField(blank=True, default=None, help_text="Whether this year's statements and trial balance carry prior-year comparatives. NULL inherits the client's own setting; True or False decides for this year alone. A year with no meaningful prior figures is a property of the year, not of the client -- turning the client switch off to fix one year would change every other year too, finalised ones included.", null=True),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='comparatives_included',
            field=models.BooleanField(blank=True, default=None, help_text="Whether comparatives were in force when this document was built. Compared against the year's current setting to tell the accountant the file on disk no longer matches. NULL means the document predates this field -- unknown, not stale, so existing documents do not all announce themselves as out of date.", null=True),
        ),
    ]
