# Generated by Django 5.2.11 on 2026-09-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_taxplanningworksheet_income_before_recoupment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustworkspace',
            name='brought_forward_losses',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Signed 4199 position: positive is a loss to recoup, negative is undistributed income brought forward', max_digits=15),
        ),
        migrations.AddField(
            model_name='trustworkspace',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='trustworkspace',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='trustworkspace',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
