# Generated by Django 5.2.11 on 2026-02-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_totp_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="email_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="invitation",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("senior_accountant", "Senior Accountant"),
                    ("accountant", "Accountant"),
                    ("office_admin", "Office Admin"),
                    ("read_only", "Read Only"),
                ],
                default="accountant",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("senior_accountant", "Senior Accountant"),
                    ("accountant", "Accountant"),
                    ("office_admin", "Office Admin"),
                    ("read_only", "Read Only"),
                ],
                default="accountant",
                max_length=20,
            ),
        ),
    ]
