# Generated by Django 5.2.11 on 2026-03-11 00:37

import config.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_invitation_email_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="totp_secret",
            field=config.encryption.EncryptedCharField(blank=True, default=""),
        ),
    ]
