# Generated by Django 5.2.11 on 2026-08-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='azure_object_id',
            field=models.CharField(blank=True, default=None, help_text='Microsoft Entra immutable object id (oid claim). Set on first SSO sign-in.', max_length=64, null=True, unique=True, verbose_name='Entra object ID'),
        ),
    ]
