"""
Regression coverage for the standalone WeasyPrint depreciation_pdf view
=======================================================================
The view at ``core/views.py:depreciation_pdf`` (URL
``/years/<uuid:pk>/depreciation/pdf/``) was patched by commit 5fc3fcc
(2026-05-21) to blank Total Cost for disposed assets in both the body
cell and the footer accumulator, sibling to the FS-pack fix in 8199c24
(Defect E). 5fc3fcc landed without test coverage; Phase E.2 discovery
identified the gap. This file adds coverage so a future regression
would fail a test rather than ship silently.

Defect E.2. See audit_hazaway_depreciation_defect_e.md,
phase_e2_fix_weasyprint_depreciation.md, and the production fix at
commit 5fc3fcc.

NOTE on weasyprint shimming: ``weasyprint`` is imported inline inside
the view (line ~9228) and its native dependency ``libgobject-2.0-0``
cannot be loaded on Windows dev machines. To keep the test portable,
the test injects a stub ``weasyprint`` module into ``sys.modules`` for
the duration of each request. The stub captures the HTML string passed
to ``weasyprint.HTML(string=...)`` so assertions run against the source
HTML — which is the exact data WeasyPrint would otherwise render into
the PDF. (``pdfplumber`` is in requirements but adds nothing here since
the HTML strings are the source of truth for the disposal logic; the
PDF is a lossy projection of the same content.)
"""
import sys
from datetime import date
from decimal import Decimal
from unittest.mock import patch

from django.test import Client, TestCase, override_settings

from accounts.models import User
from core.models import (
    Client as ClientModel,
    DepreciationAsset,
    Entity,
    FinancialYear,
)


STORAGES_OVERRIDE = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
}


class _CapturingWeasyHtml:
    """Stand-in for ``weasyprint.HTML``. Captures the HTML string passed
    to it via the ``string`` kwarg into the module-level ``_captured``
    dict, and returns a write_pdf-capable stub so the view's
    ``HttpResponse(pdf_bytes, content_type='application/pdf')`` line
    still produces a parseable response.
    """

    _captured = {}

    def __init__(self, string=None, **_kw):
        _CapturingWeasyHtml._captured["html"] = string or ""

    def write_pdf(self):
        return b"%PDF-1.4 stub generated by test\n%%EOF"


def _stub_weasyprint_module():
    """Build a fake ``weasyprint`` module exposing only ``HTML``."""
    import types
    mod = types.ModuleType("weasyprint")
    mod.HTML = _CapturingWeasyHtml
    return mod


@override_settings(STORAGES=STORAGES_OVERRIDE)
class DepreciationPdfDisposalTests(TestCase):
    """4 cases for the disposal-aware Total Cost gating in depreciation_pdf.

    Mirrors Phase E's docx-renderer suite at
    ``core/tests_fs_template_service_depreciation_report.py`` — same
    asset patterns (active, fully-depreciated-but-owned, disposed) plus
    a footer-aggregate check.
    """

    @classmethod
    def setUpTestData(cls):
        # Admin user with 2FA satisfied (Require2FAMiddleware checks
        # has_2fa = bool(totp_secret) and totp_confirmed).
        cls.user = User.objects.create_user(
            username="depreciation_pdf_test_admin",
            password="x",
            role=User.Role.ADMIN,
            totp_secret="dummy-secret-for-test",
            totp_confirmed=True,
        )

        cls.client_obj = ClientModel.objects.create(name="Depreciation PDF Test Client")
        cls.entity = Entity.objects.create(
            entity_name="Depreciation PDF Test Co Pty Ltd",
            entity_type="company",
            client=cls.client_obj,
            primary_accountant=cls.user,
        )
        cls.fy = FinancialYear.objects.create(
            entity=cls.entity,
            year_label="FY2025",
            start_date=date(2024, 7, 1),
            end_date=date(2025, 6, 30),
        )

        # Asset 1: actively depreciating (matches Hazaway "Fuso Fighter" pattern)
        cls.active = DepreciationAsset.objects.create(
            financial_year=cls.fy,
            category="General Pool",
            asset_name="Active Asset",
            total_cost=Decimal("100000.00"),
            opening_wdv=Decimal("60000.00"),
            depreciation_amount=Decimal("18000.00"),
            closing_wdv=Decimal("42000.00"),
            rate=Decimal("30.00"),
            disposal_date=None,
        )
        # Asset 2: fully depreciated but still owned (Hazaway "Ford Ranger" pattern)
        cls.fully_dep = DepreciationAsset.objects.create(
            financial_year=cls.fy,
            category="General Pool",
            asset_name="Fully Depreciated Asset",
            total_cost=Decimal("50000.00"),
            opening_wdv=Decimal("0"),
            depreciation_amount=Decimal("0"),
            closing_wdv=Decimal("0"),
            rate=Decimal("30.00"),
            disposal_date=None,
        )
        # Asset 3: disposed during CY (Hazaway "Jayco / Porsche" pattern)
        cls.disposed = DepreciationAsset.objects.create(
            financial_year=cls.fy,
            category="General Pool",
            asset_name="Disposed Asset",
            total_cost=Decimal("80000.00"),
            opening_wdv=Decimal("40000.00"),
            depreciation_amount=Decimal("0"),
            closing_wdv=Decimal("0"),
            rate=Decimal("30.00"),
            disposal_date=date(2024, 9, 1),
            disposal_consideration=Decimal("45000.00"),
        )

    def setUp(self):
        # Reset the module-level capture between tests so each test sees
        # its own render.
        _CapturingWeasyHtml._captured = {}
        self.test_client = Client()
        self.test_client.force_login(self.user)

    def _render_and_capture(self):
        """Drive the view via the test client with weasyprint stubbed.

        Returns ``(response, html_string)``.
        """
        with patch.dict(sys.modules, {"weasyprint": _stub_weasyprint_module()}):
            # secure=True bypasses SECURE_SSL_REDIRECT (DEBUG=False in tests).
            response = self.test_client.get(
                f"/years/{self.fy.pk}/depreciation/pdf/", secure=True,
            )
        self.assertEqual(
            response.status_code, 200,
            f"depreciation_pdf returned {response.status_code}; "
            f"body={response.content[:500]!r}",
        )
        html = _CapturingWeasyHtml._captured.get("html", "")
        self.assertTrue(html, "weasyprint stub never received a string=html call")
        return response, html

    @staticmethod
    def _row_for(html, asset_name):
        """Slice the HTML to the single ``<tr>...</tr>`` containing the
        asset name. Returns the row text, or '' if not found.
        """
        # Each asset row begins with an indented <tr> tag in the template
        # at line ~9277. Find the asset name, walk back to the preceding
        # <tr, walk forward to the closing </tr>.
        idx = html.find(asset_name)
        if idx == -1:
            return ""
        start = html.rfind("<tr", 0, idx)
        end = html.find("</tr>", idx)
        if start == -1 or end == -1:
            return ""
        return html[start:end + len("</tr>")]

    def test_active_asset_retains_total_cost(self):
        _, html = self._render_and_capture()
        row = self._row_for(html, "Active Asset")
        self.assertIn(
            "$100,000.00", row,
            f"Active Asset row must show Total Cost $100,000.00; row={row!r}",
        )

    def test_fully_depreciated_asset_retains_total_cost(self):
        _, html = self._render_and_capture()
        row = self._row_for(html, "Fully Depreciated Asset")
        self.assertIn(
            "$50,000.00", row,
            f"Fully Depreciated Asset row must show Total Cost $50,000.00 "
            f"(no disposal_date so the gate must NOT blank it); row={row!r}",
        )

    def test_disposed_asset_blanks_total_cost(self):
        _, html = self._render_and_capture()
        row = self._row_for(html, "Disposed Asset")
        # The disposed asset row must NOT contain "$80,000.00" anywhere —
        # the Total Cost cell must be blank. Other cells in the row
        # (opening WDV $40,000.00, disposal_amt $40,000.00, etc.) have
        # different amounts so this substring check is unambiguous.
        self.assertNotIn(
            "$80,000.00", row,
            f"Disposed Asset row must blank Total Cost; "
            f"$80,000.00 should not appear; row={row!r}",
        )

    def test_footer_total_cost_excludes_disposed(self):
        _, html = self._render_and_capture()
        # Footer expected: active $100,000.00 + fully_dep $50,000.00 = $150,000.00.
        # Disposed $80,000.00 is excluded → $230,000.00 would appear if the
        # accumulator gate is missing.
        # The footer row is the only place "Totals" appears as a cell.
        totals_idx = html.find("Totals")
        self.assertGreater(totals_idx, -1, "Footer 'Totals' row not found in HTML")
        footer_end = html.find("</tr>", totals_idx)
        footer_row = html[totals_idx:footer_end] if footer_end > -1 else html[totals_idx:]
        self.assertIn(
            "$150,000.00", footer_row,
            f"Footer Total Cost must be $150,000.00 (active 100k + fully-dep 50k, "
            f"disposed 80k excluded); footer={footer_row!r}",
        )
        self.assertNotIn(
            "$230,000.00", footer_row,
            f"Footer Total Cost must NOT include the disposed asset; "
            f"$230,000.00 indicates the gate is missing; footer={footer_row!r}",
        )
