"""
Trust default chart of accounts — account range alias seed data.

Defines the HandiLedger-style alias taxonomy used when preparing financial
statements for trust entities. Each row is a tuple of
    (section, alias, description, dc_sign, range_from, range_to)
where dc_sign is "D" (Debit) or "C" (Credit).

Sections are grouping labels only — aliases are keyed globally on
(entity_type="trust", alias) in the AccountRangeAlias table.

Seeded via `python manage.py seed_trust_coa`.
"""

# Section labels (used as the `section` column on AccountRangeAlias)
SECTION_REVENUE = "Revenue"
SECTION_EXPENSES = "Expenses"
SECTION_CURRENT_ASSETS = "Current Assets"
SECTION_NON_CURRENT_ASSETS = "Non-Current Assets"
SECTION_CURRENT_LIABILITIES = "Current Liabilities"
SECTION_NON_CURRENT_LIABILITIES = "Non-Current Liabilities"
SECTION_CAPITAL_ACCOUNTS = "Capital Accounts"
SECTION_PL_APPROPRIATION = "P&L Appropriation"
SECTION_EQUITY_TRUST = "Equity / Trust-Specific"


TRUST_ACCOUNT_RANGE_ALIASES = [
    # ======================================================================
    # Revenue
    # ======================================================================
    (SECTION_REVENUE, "RevAll", "Revenue", "C", "0001", "0999"),
    (SECTION_REVENUE, "RevMan", "Manufacturing income", "C", "0001", "0099"),
    (SECTION_REVENUE, "RevTrading", "Trading income", "C", "0100", "0199"),
    (SECTION_REVENUE, "RevLivestock", "Livestock sales", "C", "0200", "0209"),
    (SECTION_REVENUE, "StockMovement", "Stock movement", "C", "0210", "0210"),
    (SECTION_REVENUE, "RevPP", "Primary production", "C", "0300", "0399"),
    (SECTION_REVENUE, "RevPpTrad", "Primary production trading", "C", "0400", "0409"),
    (SECTION_REVENUE, "RevPP2", "Primary production", "C", "0410", "0499"),
    (SECTION_REVENUE, "RevOther", "Other", "C", "0500", "0699"),
    (SECTION_REVENUE, "RevRental", "Rent received", "C", "0700", "0715"),
    (SECTION_REVENUE, "RevOtherB", "Other income", "C", "0716", "0999"),
    (SECTION_REVENUE, "RevSales", "Other sales revenue", "C", "0500", "0519"),
    (SECTION_REVENUE, "RevDistPartnership", "Distribution from partnerships", "C", "0380", "0380"),
    (SECTION_REVENUE, "RevDistTrust", "Distribution from trusts", "C", "0382", "0382"),
    (SECTION_REVENUE, "RevDividends", "Dividends - Franked", "C", "0550", "0550"),
    (SECTION_REVENUE, "RevDistPshipNPP", "Distributions from partnerships", "C", "0565", "0565"),
    (SECTION_REVENUE, "RevDistTrustNPP", "Distributions from trusts", "C", "0567", "0567"),
    (SECTION_REVENUE, "RevInterest", "Interest", "C", "0575", "0575"),
    (SECTION_REVENUE, "RevForeignIncome", "Net foreign income", "C", "0578", "0578"),
    (SECTION_REVENUE, "RevForExch", "Foreign exchange profit", "C", "0580", "0580"),
    (SECTION_REVENUE, "RevAssetSale", "Profit on sale of assets", "C", "0600", "0601"),
    (SECTION_REVENUE, "RevRent", "Rental income", "C", "0620", "0620"),
    (SECTION_REVENUE, "RevRoyalty", "Royalty income", "C", "0625", "0625"),
    (SECTION_REVENUE, "RevGovSubsidy", "Government subsidies received", "C", "0640", "0640"),
    (SECTION_REVENUE, "RevPpsPP", "PPS income - PP", "C", "0486", "0486"),
    (SECTION_REVENUE, "RevPpsNPP", "PPS income - NPP", "C", "0586", "0586"),
    (SECTION_REVENUE, "RevRpsPP", "RPS income - PP", "C", "0495", "0495"),
    (SECTION_REVENUE, "RevRpsNpp", "RPS income - NPP", "C", "0628", "0628"),
    (SECTION_REVENUE, "RevOtherPP", "Other sales - PP", "C", "0430", "0480"),
    (SECTION_REVENUE, "RevHire", "Hire income", "C", "0562", "0562"),
    (SECTION_REVENUE, "RevLease", "Lease income", "C", "0585", "0585"),
    (SECTION_REVENUE, "RevAGIPs", "Assessable government industry payments - PP", "C", "0320", "0320"),
    (SECTION_REVENUE, "RevAGIPsNpp", "Assessable government industry payments - NPP", "C", "0525", "0525"),
    (SECTION_REVENUE, "RevFBT", "FBT employee contributions", "C", "0569", "0569"),
    (SECTION_REVENUE, "RevNoAbnPP", "Gross payments where ABN not quoted PP", "C", "0482", "0482"),
    (SECTION_REVENUE, "RevVolAgreementPP", "Gross payments - Voluntary agreement PP", "C", "0483", "0483"),
    (SECTION_REVENUE, "RevLabourHirePP", "Gross payments - Labour hire or other payments PP", "C", "0484", "0484"),
    (SECTION_REVENUE, "RevNoAbnNPP", "Gross payments where ABN not quoted NPP", "C", "0558", "0558"),
    (SECTION_REVENUE, "RevVolAgreementNPP", "Gross payments - Voluntary agreement NPP", "C", "0559", "0559"),
    (SECTION_REVENUE, "RevLabourHireNPP", "Gross payments - Labour hire or other payments NPP", "C", "0561", "0561"),
    (SECTION_REVENUE, "RevUnDividends", "Dividends - Unfranked", "C", "0551", "0551"),
    (SECTION_REVENUE, "RevNonOperating", "Non-operating revenue", "C", "0597", "0602"),
    (SECTION_REVENUE, "RevSaleReceivable", "Profit on sale of receivables", "C", "0597", "0597"),
    (SECTION_REVENUE, "RevSaleInvest", "Profit on sale of investments", "C", "0598", "0598"),
    (SECTION_REVENUE, "RevSaleIntangible", "Profit on sale of intangibles", "C", "0599", "0599"),
    (SECTION_REVENUE, "RevSalePPE", "Profit on sale of property, plant & equipment", "C", "0600", "0600"),
    (SECTION_REVENUE, "RevCapitalGain", "Capital gains on sale of asset", "C", "0601", "0601"),

    # ======================================================================
    # Expenses
    # ======================================================================
    (SECTION_EXPENSES, "ExpAll", "Expenses", "D", "1000", "1999"),
    (SECTION_EXPENSES, "ExpManOpWIP", "Manufacturing - Opening work in progress", "D", "1000", "1004"),
    (SECTION_EXPENSES, "ExpManOpRaw", "Manufacturing - Opening raw materials", "D", "1005", "1009"),
    (SECTION_EXPENSES, "ExpManExpDr", "Manufacturing - Expenses", "D", "1010", "1025"),
    (SECTION_EXPENSES, "ExpManCostsCr", "Manufacturing - Cost of manufacturing CR", "D", "1026", "1029"),
    (SECTION_EXPENSES, "ExpManClWIP", "Manufacturing - Closing work in progress", "C", "1030", "1034"),
    (SECTION_EXPENSES, "ExpManClRaw", "Manufacturing - Closing raw materials", "C", "1035", "1039"),
    (SECTION_EXPENSES, "ExpManExpCr", "Manufacturing - Expenses", "C", "1040", "1099"),
    (SECTION_EXPENSES, "ExpTradOpRaw", "Trading - Opening raw materials", "D", "1100", "1104"),
    (SECTION_EXPENSES, "ExpTradOpWIP", "Trading - Opening work in progress", "D", "1105", "1107"),
    (SECTION_EXPENSES, "ExpTradOpFin", "Trading - Opening finished goods", "D", "1108", "1109"),
    (SECTION_EXPENSES, "ExpTradExp1", "Trading - Expenses", "D", "1110", "1125"),
    (SECTION_EXPENSES, "ExpTradCostCr", "Trading - Cost of trading CR", "C", "1126", "1129"),
    (SECTION_EXPENSES, "ExpTradClRaw", "Trading - Closing raw materials", "C", "1130", "1134"),
    (SECTION_EXPENSES, "ExpTradClWIP", "Trading - Closing work in progress", "C", "1135", "1137"),
    (SECTION_EXPENSES, "ExpTradClFin", "Trading - Closing finished goods", "C", "1138", "1139"),
    (SECTION_EXPENSES, "ExpTradExp2", "Trading - Expenses", "D", "1140", "1199"),
    (SECTION_EXPENSES, "ExpLiveOpStock", "Livestock - Opening stock", "D", "1200", "1209"),
    (SECTION_EXPENSES, "ExpLivePurch", "Livestock - Purchases", "D", "1210", "1219"),
    (SECTION_EXPENSES, "ExpLiveNatInc", "Livestock - Natural increase", "D", "1220", "1229"),
    (SECTION_EXPENSES, "ExpLiveRat", "Livestock - Rations", "C", "1230", "1239"),
    (SECTION_EXPENSES, "ExpLiveClStock", "Livestock - Closing stock", "C", "1240", "1249"),
    (SECTION_EXPENSES, "ExpLiveLoss", "Livestock - Losses", "C", "1250", "1259"),
    (SECTION_EXPENSES, "ExpPpTradOpStock", "Primary production trading - Opening stock", "D", "1260", "1269"),
    (SECTION_EXPENSES, "ExpPpTradPurch", "Primary production trading - Purchases", "D", "1270", "1279"),
    (SECTION_EXPENSES, "ExpPpTradClStock", "Primary production trading - Closing stock", "C", "1280", "1289"),
    (SECTION_EXPENSES, "ExpPpTradOthExp", "Primary production trading - Other expenses", "D", "1290", "1299"),
    (SECTION_EXPENSES, "ExpPpExp", "Primary production - Expenses", "D", "1300", "1499"),
    (SECTION_EXPENSES, "ExpOther", "Other expenses", "D", "1500", "1984"),
    (SECTION_EXPENSES, "ExpRent", "Rental expenses", "D", "1985", "1999"),
    (SECTION_EXPENSES, "ExpHpPp", "Hire purchase charges - Primary production", "D", "1364", "1364"),
    (SECTION_EXPENSES, "ExpIntPp", "Interest - Primary production", "D", "1372", "1373"),
    (SECTION_EXPENSES, "ExpIntPpMV", "Interest - Primary production motor vehicle", "D", "1386", "1386"),
    (SECTION_EXPENSES, "ExpIntPPMV2", "Interest - Primary production motor vehicle - Commercial", "D", "1393", "1393"),
    (SECTION_EXPENSES, "ExpIntPpMV3", "Interest - Primary production motor vehicle - Other", "D", "1400", "1400"),
    (SECTION_EXPENSES, "ExpBorrCosts", "Borrowing costs", "D", "1550", "1550"),
    (SECTION_EXPENSES, "ExpHirePurch", "Hire purchase charges", "D", "1745", "1745"),
    (SECTION_EXPENSES, "ExpInt", "Interest", "D", "1760", "1761"),
    (SECTION_EXPENSES, "ExpLease", "Lease payments", "D", "1775", "1775"),
    (SECTION_EXPENSES, "ExpIntMV", "Interest - Motor vehicle", "D", "1805", "1805"),
    (SECTION_EXPENSES, "ExpIntMV2", "Interest - Motor vehicle - Commercial", "D", "1812", "1812"),
    (SECTION_EXPENSES, "ExpIntMV3", "Interest - Motor vehicle - Other", "D", "1819", "1819"),
    (SECTION_EXPENSES, "ExpBadDebtPp", "Bad debts", "D", "1306", "1306"),
    (SECTION_EXPENSES, "ExpBadDebt", "Bad debts", "D", "1540", "1540"),
    (SECTION_EXPENSES, "ExpDepnBuildings", "Depreciation - Buildings", "D", "1616", "1616"),
    (SECTION_EXPENSES, "ExpDepnPlantPp", "Depreciation - Plant & equipment - PP", "D", "1318", "1318"),
    (SECTION_EXPENSES, "ExpDepnPlantMan", "Depreciation - Plant & equipment - Man", "D", "1045", "1045"),
    (SECTION_EXPENSES, "ExpDepnPlant", "Depreciation - Plant & equipment", "D", "1615", "1615"),
    (SECTION_EXPENSES, "ExpDepnMVPp", "Depreciation - Motor vehicles - PP", "D", "1384", "1384"),
    (SECTION_EXPENSES, "ExpDepnMVPPCom", "Depreciation - Motor vehicles - PP commercial", "D", "1391", "1391"),
    (SECTION_EXPENSES, "ExpDepnMVPPOther", "Depreciation - Motor vehicles - PP other", "D", "1398", "1398"),
    (SECTION_EXPENSES, "ExpDepnMV", "Depreciation - Motor vehicles", "D", "1803", "1803"),
    (SECTION_EXPENSES, "ExpDepnMVCom", "Depreciation - Motor vehicles - Commercial", "D", "1810", "1810"),
    (SECTION_EXPENSES, "ExpDepnMVOther", "Depreciation - Motor vehicles - Other", "D", "1817", "1817"),
    (SECTION_EXPENSES, "ExpDepnOther", "Depreciation - Other", "D", "1617", "1617"),
    (SECTION_EXPENSES, "ExpResearch", "Research & development", "D", "1871", "1871"),
    (SECTION_EXPENSES, "ExpAudit", "Auditors - Audit", "D", "1535", "1535"),
    (SECTION_EXPENSES, "ExpAuditOther", "Auditors - Other", "D", "1536", "1536"),
    (SECTION_EXPENSES, "ExpDivDeductions", "Dividend deductions", "D", "1643", "1643"),
    (SECTION_EXPENSES, "ExpIntDeductions", "Interest deductions", "D", "1763", "1763"),
    (SECTION_EXPENSES, "ExpRentInterest", "Rental interest deductions", "D", "1989", "1989"),
    (SECTION_EXPENSES, "ExpRoyaltyDeductions", "Royalty deductions", "D", "1872", "1872"),
    (SECTION_EXPENSES, "ExpPshipTrustDedPP", "Partnership/Trust deductions - PP", "D", "1412", "1412"),
    (SECTION_EXPENSES, "ExpPshipTrustDedNPP", "Partnership/Trust deductions - NPP", "D", "1824", "1824"),
    (SECTION_EXPENSES, "ExpContractorsMan", "Contractor, sub-contractor & commission", "D", "1047", "1047"),
    (SECTION_EXPENSES, "ExpContractorsTrad", "Contractor, sub-contractor & commission", "D", "1165", "1165"),
    (SECTION_EXPENSES, "ExpContractorsPP", "Contractor, sub-contractor & commission", "D", "1313", "1317"),
    (SECTION_EXPENSES, "ExpContractorsPP2", "Contractor, sub-contractor & commission", "D", "1334", "1334"),
    (SECTION_EXPENSES, "ExpContractorsPP3", "Contractor, sub-contractor & commission", "D", "1452", "1452"),
    (SECTION_EXPENSES, "ExpContractorsOther1", "Contractor, sub-contractor & commission", "D", "1575", "1576"),
    (SECTION_EXPENSES, "ExpContractorsOther2", "Contractor, sub-contractor & commission", "D", "1585", "1585"),
    (SECTION_EXPENSES, "ExpContractorsOther3", "Contractor, sub-contractor & commission", "D", "1590", "1590"),
    (SECTION_EXPENSES, "ExpContractorsOther4", "Contractor, sub-contractor & commission", "D", "1670", "1670"),
    (SECTION_EXPENSES, "ExpContractorsOther5", "Contractor, sub-contractor & commission", "D", "1927", "1927"),
    (SECTION_EXPENSES, "ExpEmployeeSuperPP", "Employee superannuation", "D", "1458", "1459"),
    (SECTION_EXPENSES, "ExpEmployeeSuperNPP", "Employee superannuation", "D", "1935", "1936"),
    (SECTION_EXPENSES, "ExpLeasePP", "Lease expenses within Australia", "D", "1374", "1374"),
    (SECTION_EXPENSES, "ExpLeaseCarPP", "Motor vehicle car - Lease within Australia", "D", "1387", "1387"),
    (SECTION_EXPENSES, "ExpLeaseCommPP", "Motor vehicle commercial - Lease within Australia", "D", "1394", "1394"),
    (SECTION_EXPENSES, "ExpMvOtherPP", "Motor vehicle other - Lease within Australia", "D", "1401", "1401"),
    (SECTION_EXPENSES, "ExpLeaseNPP", "Lease expenses within Australia - NPP", "D", "1775", "1775"),
    (SECTION_EXPENSES, "ExpLeaseCarNPP", "Motor vehicle car - Lease within Australia - NPP", "D", "1806", "1806"),
    (SECTION_EXPENSES, "ExpLeaseCommNpp", "Motor vehicle commercial - Lease within Australia - NPP", "D", "1813", "1813"),
    (SECTION_EXPENSES, "ExpLeaseOtherNPP", "Motor vehicle other - Lease within Australia - NPP", "D", "1820", "1820"),
    (SECTION_EXPENSES, "ExpLeaseOverseasPP", "Lease expenses - Overseas - PP", "D", "1377", "1377"),
    (SECTION_EXPENSES, "ExpLeaseOverseasNPP", "Lease expenses - Overseas - NPP", "D", "1777", "1777"),
    (SECTION_EXPENSES, "ExpRentPP", "Rent expenses - PP", "D", "1422", "1422"),
    (SECTION_EXPENSES, "ExpRentNPP", "Rent expenses - NPP", "D", "1855", "1855"),
    (SECTION_EXPENSES, "ExpRoyaltyPaytPP", "Royalty expenses - PP", "D", "1432", "1433"),
    (SECTION_EXPENSES, "ExpRoyaltyPaytNpp", "Royalty expenses - NPP", "D", "1873", "1874"),
    (SECTION_EXPENSES, "ExpMvPP", "Motor vehicle expenses - PP", "D", "1384", "1404"),
    (SECTION_EXPENSES, "ExpMvNpp", "Motor vehicle expenses - NPP", "D", "1803", "1823"),
    (SECTION_EXPENSES, "ExpRepairsPP", "Repairs & maintenance - PP", "D", "1426", "1426"),
    (SECTION_EXPENSES, "ExpRepairsNpp", "Repairs & maintenance - NPP", "D", "1865", "1865"),
    (SECTION_EXPENSES, "ExpSalaryManDirLab", "Salary - Direct labour", "D", "1040", "1040"),
    (SECTION_EXPENSES, "ExpSalaryTradDirLab", "Salary - Direct labour (trading)", "D", "1160", "1160"),
    (SECTION_EXPENSES, "ExpSalaryCasualPP", "Salary - Casual labour PP", "D", "1310", "1310"),
    (SECTION_EXPENSES, "ExpSalaryCommPP", "Salary - Commissions PP", "D", "1313", "1314"),
    (SECTION_EXPENSES, "ExpSalaryPP", "Salaries", "D", "1434", "1435"),
    (SECTION_EXPENSES, "ExpSalaryCasualNPP", "Salary - Casual labour NPP", "D", "1560", "1560"),
    (SECTION_EXPENSES, "ExpSalaryCommNPP", "Salary - Commissions NPP", "D", "1575", "1576"),
    (SECTION_EXPENSES, "ExpSalaryDirFees", "Salary - Directors fees", "D", "1625", "1625"),
    (SECTION_EXPENSES, "ExpSalaryDirSal", "Salary - Directors salaries", "D", "1630", "1630"),
    (SECTION_EXPENSES, "ExpSalaryNPP", "Salaries - NPP", "D", "1880", "1880"),
    (SECTION_EXPENSES, "ExpSalaryAssNPP", "Salaries - Associated persons - NPP", "D", "1885", "1885"),
    (SECTION_EXPENSES, "ExpSalaryWages", "Wages", "D", "1965", "1965"),
    (SECTION_EXPENSES, "ExpAssociatedSuperPP", "Payments to associated persons - Superannuation", "D", "1459", "1459"),
    (SECTION_EXPENSES, "ExpAssociatedSupNPP", "Payments to associated persons - Superannuation", "D", "1936", "1936"),
    (SECTION_EXPENSES, "ExpLandDegradation", "Land degradation expenses - PP", "D", "1376", "1376"),
    (SECTION_EXPENSES, "ExpLandDegNPP", "Land degradation expenses - NPP", "D", "1768", "1768"),
    (SECTION_EXPENSES, "ExpEnviroProtectPP", "Environmental protection expenses - PP", "D", "1333", "1333"),
    (SECTION_EXPENSES, "ExpEnviroProtectNPP", "Environmental protection expenses - NPP", "D", "1665", "1665"),
    (SECTION_EXPENSES, "ExpDeficiencyTrust", "Deficiency in trust assets", "D", "1984", "1984"),
    (SECTION_EXPENSES, "ExpAmortNPP", "Amortisation NPP", "D", "1618", "1618"),
    (SECTION_EXPENSES, "ExpAmortPP", "Amortisation PP", "D", "1319", "1319"),
    (SECTION_EXPENSES, "ExpWriteDownNPP", "Write-down to recoverable amount NPP", "D", "1619", "1619"),
    (SECTION_EXPENSES, "ExpWriteDownPP", "Write-down to recoverable amount PP", "D", "1320", "1320"),

    # ======================================================================
    # Current Assets
    # ======================================================================
    (SECTION_CURRENT_ASSETS, "CaAll", "Current assets", "D", "2000", "2499"),
    (SECTION_CURRENT_ASSETS, "CaBank", "Bank account", "D", "2000", "2029"),
    (SECTION_CURRENT_ASSETS, "CaOtherCash", "Other cash items", "D", "2030", "2099"),
    (SECTION_CURRENT_ASSETS, "CaTrade", "Trade debtors", "D", "2100", "2118"),
    (SECTION_CURRENT_ASSETS, "CaProvDD", "Provision for doubtful debts", "C", "2119", "2119"),
    (SECTION_CURRENT_ASSETS, "CaBills", "Bills, promissory notes", "D", "2120", "2139"),
    (SECTION_CURRENT_ASSETS, "CaLoanDir", "Loans to directors", "D", "2140", "2149"),
    (SECTION_CURRENT_ASSETS, "CaLoanShar", "Loans to shareholders", "D", "2150", "2159"),
    (SECTION_CURRENT_ASSETS, "CaLoanHC", "Loans to holding company", "D", "2160", "2179"),
    (SECTION_CURRENT_ASSETS, "CaLoanOtherRelCo", "Loans to other related corporations", "D", "2180", "2189"),
    (SECTION_CURRENT_ASSETS, "CaOther1", "Other", "D", "2190", "2197"),
    (SECTION_CURRENT_ASSETS, "CaAssetsTrust", "Assets of trust", "D", "2198", "2198"),
    (SECTION_CURRENT_ASSETS, "CaProvDefAsTr", "Provision for deficiency", "C", "2199", "2199"),
    (SECTION_CURRENT_ASSETS, "CaListedGovStock", "Listed - Government stocks", "D", "2200", "2209"),
    (SECTION_CURRENT_ASSETS, "CaListedDeb", "Listed - Debentures", "D", "2210", "2219"),
    (SECTION_CURRENT_ASSETS, "CaListedShares", "Listed - Shares", "D", "2220", "2229"),
    (SECTION_CURRENT_ASSETS, "CaListedShareOpt", "Listed - Share options", "D", "2230", "2239"),
    (SECTION_CURRENT_ASSETS, "CaUnlistedSh", "Unlisted - Shares", "D", "2240", "2248"),
    (SECTION_CURRENT_ASSETS, "CaProvDimShares", "Provision for diminution in share value", "C", "2249", "2249"),
    (SECTION_CURRENT_ASSETS, "CaUnlistedGovSt", "Unlisted - Government stocks", "D", "2250", "2269"),
    (SECTION_CURRENT_ASSETS, "CaUnlistedDeb", "Unlisted - Debentures", "D", "2270", "2279"),
    (SECTION_CURRENT_ASSETS, "CaUnlistedShareOp", "Unlisted - Share options", "D", "2280", "2288"),
    (SECTION_CURRENT_ASSETS, "CaProvDimShOp", "Provision for diminution in share value", "C", "2289", "2289"),
    (SECTION_CURRENT_ASSETS, "CaOtherInv", "Other investments", "D", "2290", "2299"),
    (SECTION_CURRENT_ASSETS, "CaManRawMat", "Manufacturing raw materials", "D", "2300", "2304"),
    (SECTION_CURRENT_ASSETS, "CaTradRaw", "Trading raw materials", "D", "2305", "2309"),
    (SECTION_CURRENT_ASSETS, "CaLive", "Livestock on hand", "D", "2310", "2319"),
    (SECTION_CURRENT_ASSETS, "CaManWIP", "Manufacturing work in progress", "D", "2325", "2329"),
    (SECTION_CURRENT_ASSETS, "CaTradWIP", "Trading work in progress", "D", "2330", "2332"),
    (SECTION_CURRENT_ASSETS, "CaTradFinGoods", "Trading finished goods", "D", "2335", "2339"),
    (SECTION_CURRENT_ASSETS, "CaPpStock", "Primary production stock on hand", "D", "2340", "2349"),
    (SECTION_CURRENT_ASSETS, "CaFinGoodCost", "Finished goods (at cost)", "D", "2350", "2362"),
    (SECTION_CURRENT_ASSETS, "CaFinGoodNRV", "Finished goods (net realisable value)", "D", "2363", "2374"),
    (SECTION_CURRENT_ASSETS, "CaLandAq", "Land, acquisition cost", "D", "2375", "2384"),
    (SECTION_CURRENT_ASSETS, "CaLandDev", "Land, development cost", "D", "2385", "2392"),
    (SECTION_CURRENT_ASSETS, "CaLandRates", "Land, rates, taxes etc", "D", "2393", "2399"),
    (SECTION_CURRENT_ASSETS, "CaShortDep", "Short term deposits", "D", "2400", "2424"),
    (SECTION_CURRENT_ASSETS, "CaPrep", "Prepayments", "D", "2425", "2449"),
    (SECTION_CURRENT_ASSETS, "CaFITB", "Future income tax benefit", "D", "2450", "2474"),
    (SECTION_CURRENT_ASSETS, "CaOther2", "Other", "D", "2475", "2499"),

    # ======================================================================
    # Non-Current Assets
    # ======================================================================
    (SECTION_NON_CURRENT_ASSETS, "NcaAll", "Non-Current Assets", "D", "2500", "2999"),
    (SECTION_NON_CURRENT_ASSETS, "NcaBills", "Bills, promissory notes", "D", "2500", "2519"),
    (SECTION_NON_CURRENT_ASSETS, "NcaLoanDir", "Loans to directors", "D", "2520", "2529"),
    (SECTION_NON_CURRENT_ASSETS, "NcaLoanShar", "Loans to shareholders", "D", "2530", "2539"),
    (SECTION_NON_CURRENT_ASSETS, "NcaLoanHC", "Loans to holding company", "D", "2540", "2559"),
    (SECTION_NON_CURRENT_ASSETS, "NcaLoanOtherRelCo", "Loans to related companies", "D", "2560", "2579"),
    (SECTION_NON_CURRENT_ASSETS, "NcaLoanOtherPer", "Loans to other persons", "D", "2580", "2599"),
    (SECTION_NON_CURRENT_ASSETS, "NcaListedGovStock", "Listed - Government stocks", "D", "2600", "2608"),
    (SECTION_NON_CURRENT_ASSETS, "NcaListedDeb", "Listed - Debentures", "D", "2609", "2617"),
    (SECTION_NON_CURRENT_ASSETS, "NcaListedShares", "Listed - Shares", "D", "2618", "2626"),
    (SECTION_NON_CURRENT_ASSETS, "NcaListedShareOpt", "Listed - Share options", "D", "2627", "2635"),
    (SECTION_NON_CURRENT_ASSETS, "NcaUnDeb", "Unlisted - Debentures", "D", "2636", "2644"),
    (SECTION_NON_CURRENT_ASSETS, "NcaUnSharesSub", "Unlisted - Shares in subsidiary companies", "D", "2645", "2653"),
    (SECTION_NON_CURRENT_ASSETS, "NcaUnSharesRelCo", "Unlisted - Shares in related companies", "D", "2654", "2662"),
    (SECTION_NON_CURRENT_ASSETS, "NcaUnSharesAssCo", "Unlisted - Share in associated companies", "D", "2663", "2671"),
    (SECTION_NON_CURRENT_ASSETS, "NcaUnSharesOth", "Unlisted - Shares in other companies", "D", "2672", "2679"),
    (SECTION_NON_CURRENT_ASSETS, "NcaUnProvDim", "Provision for diminution in share value", "C", "2680", "2680"),
    (SECTION_NON_CURRENT_ASSETS, "NcaUnShareOpt", "Unlisted - Share options", "D", "2681", "2690"),
    (SECTION_NON_CURRENT_ASSETS, "NcaUnPship", "Unlisted - Partnership", "D", "2691", "2694"),
    (SECTION_NON_CURRENT_ASSETS, "NcaOther1", "Other", "D", "2695", "2699"),
    (SECTION_NON_CURRENT_ASSETS, "NcaRawMat", "Raw materials", "D", "2700", "2724"),
    (SECTION_NON_CURRENT_ASSETS, "NcaWIP", "Work in progress", "D", "2725", "2749"),
    (SECTION_NON_CURRENT_ASSETS, "NcaFinGoodCost", "Finished goods (cost)", "D", "2750", "2762"),
    (SECTION_NON_CURRENT_ASSETS, "NcaFinGoodsVal", "Finished goods (value)", "D", "2763", "2774"),
    (SECTION_NON_CURRENT_ASSETS, "NcaLandAq", "Land, acquisition cost", "D", "2775", "2784"),
    (SECTION_NON_CURRENT_ASSETS, "NcaLandDev", "Land, development cost", "D", "2785", "2792"),
    (SECTION_NON_CURRENT_ASSETS, "NcaLandRates", "Land, rates, taxes etc", "D", "2793", "2799"),
    (SECTION_NON_CURRENT_ASSETS, "NcaFreeLandCost", "Freehold land (cost)", "D", "2800", "2804"),
    (SECTION_NON_CURRENT_ASSETS, "NcaFreeLandDirVal", "Freehold land (directors valuation)", "D", "2805", "2809"),
    (SECTION_NON_CURRENT_ASSETS, "NcaFreeLandIndVal", "Freehold land (independent valuation)", "D", "2810", "2814"),
    (SECTION_NON_CURRENT_ASSETS, "NcaBuildCost", "Buildings (cost)", "D", "2815", "2819"),
    (SECTION_NON_CURRENT_ASSETS, "NcaBuildDirVal", "Buildings (directors valuation)", "D", "2820", "2824"),
    (SECTION_NON_CURRENT_ASSETS, "NcaBuildIndVal", "Buildings (independent valuation)", "D", "2825", "2828"),
    (SECTION_NON_CURRENT_ASSETS, "NcaBuildAccDep", "Buildings accumulated depreciation", "C", "2829", "2829"),
    (SECTION_NON_CURRENT_ASSETS, "NcaLeaseImpCost", "Lease improvements (cost)", "D", "2830", "2833"),
    (SECTION_NON_CURRENT_ASSETS, "NcaLeaseAccDep", "Lease accumulated depreciation", "C", "2834", "2834"),
    (SECTION_NON_CURRENT_ASSETS, "NcaLeaseImpCostB", "Lease improvements (cost)", "D", "2835", "2838"),
    (SECTION_NON_CURRENT_ASSETS, "NcaLeaseAccDepB", "Lease accumulated depreciation", "C", "2839", "2839"),
    (SECTION_NON_CURRENT_ASSETS, "NcaLeaseImpCostC", "Lease improvements (cost)", "D", "2840", "2842"),
    (SECTION_NON_CURRENT_ASSETS, "NcaLeaseAccDepC", "Lease accumulated depreciation", "C", "2843", "2843"),
    (SECTION_NON_CURRENT_ASSETS, "NcaLeaseOther", "Lease improvements (other)", "D", "2844", "2848"),
    (SECTION_NON_CURRENT_ASSETS, "NcaLeaseAccDepD", "Lease accumulated depreciation", "C", "2849", "2849"),
    (SECTION_NON_CURRENT_ASSETS, "NcaPlCost", "Plant & equipment (cost)", "D", "2850", "2858"),
    (SECTION_NON_CURRENT_ASSETS, "NcaPlAccDep", "Plant accumulated depreciation", "C", "2859", "2859"),
    (SECTION_NON_CURRENT_ASSETS, "NcaPlCostB", "Plant & equipment (cost)", "D", "2860", "2868"),
    (SECTION_NON_CURRENT_ASSETS, "NcaPlAccDepB", "Plant accumulated depreciation", "C", "2869", "2869"),
    (SECTION_NON_CURRENT_ASSETS, "NcaPlLease", "Plant & equipment (lease)", "D", "2870", "2874"),
    (SECTION_NON_CURRENT_ASSETS, "NcaPlLeaseAccDep", "Plant & equipment (lease) amortisation", "C", "2875", "2875"),
    (SECTION_NON_CURRENT_ASSETS, "NcaPlOther", "Plant (other)", "D", "2876", "2879"),
    (SECTION_NON_CURRENT_ASSETS, "NcaPlOtherAccDep", "Plant (other) accumulated depreciation", "C", "2880", "2880"),
    (SECTION_NON_CURRENT_ASSETS, "NcaPlOtherB", "Plant (other)", "D", "2881", "2884"),
    (SECTION_NON_CURRENT_ASSETS, "NcaPlOtherAccDepB", "Plant (other) accumulated depreciation", "C", "2885", "2885"),
    (SECTION_NON_CURRENT_ASSETS, "NcaPlOtherC", "Plant (other)", "D", "2886", "2888"),
    (SECTION_NON_CURRENT_ASSETS, "NcaPlOtherAccDepC", "Plant (other) accumulated depreciation", "C", "2889", "2889"),
    (SECTION_NON_CURRENT_ASSETS, "NcaMotorCost", "Motor vehicles (cost)", "D", "2890", "2894"),
    (SECTION_NON_CURRENT_ASSETS, "NcaMotorAccDep", "Motor accumulated depreciation", "C", "2895", "2895"),
    (SECTION_NON_CURRENT_ASSETS, "NcaMotorCostB", "Motor vehicles (cost)", "D", "2896", "2896"),
    (SECTION_NON_CURRENT_ASSETS, "NcaMotorAccDepB", "Motor accumulated depreciation", "C", "2897", "2897"),
    (SECTION_NON_CURRENT_ASSETS, "NcaMotorCostC", "Motor vehicles (cost)", "D", "2898", "2898"),
    (SECTION_NON_CURRENT_ASSETS, "NcaMotorAccDepC", "Motor accumulated depreciation", "C", "2899", "2899"),
    (SECTION_NON_CURRENT_ASSETS, "NcaOther", "Other - Assets", "D", "2900", "2923"),
    (SECTION_NON_CURRENT_ASSETS, "NcaOtherAccDep", "Other - Assets accumulated depreciation", "C", "2924", "2924"),
    (SECTION_NON_CURRENT_ASSETS, "NcaGood", "Goodwill", "D", "2925", "2928"),
    (SECTION_NON_CURRENT_ASSETS, "NcaGoodAccDep", "Goodwill accumulated amortisation", "C", "2929", "2929"),
    (SECTION_NON_CURRENT_ASSETS, "NcaPat", "Patents & trademarks", "D", "2930", "2933"),
    (SECTION_NON_CURRENT_ASSETS, "NcaParAccAm", "Patents accumulated amortisation", "C", "2934", "2934"),
    (SECTION_NON_CURRENT_ASSETS, "NcaOtherInt", "Other intangibles", "D", "2935", "2938"),
    (SECTION_NON_CURRENT_ASSETS, "NcaOtherIntAmort", "Other intangibles amortisation", "C", "2939", "2939"),
    (SECTION_NON_CURRENT_ASSETS, "NcaOtherIntB", "Other intangibles", "D", "2940", "2948"),
    (SECTION_NON_CURRENT_ASSETS, "NcaOtherIntAmortB", "Other intangibles amortisation", "C", "2949", "2949"),
    (SECTION_NON_CURRENT_ASSETS, "NcaPrelim", "Preliminary expenses", "D", "2950", "2958"),
    (SECTION_NON_CURRENT_ASSETS, "NcaPrelimAmort", "Preliminary expenses accumulated amortisation", "C", "2959", "2959"),
    (SECTION_NON_CURRENT_ASSETS, "NcaShareIs", "Share issue expenses", "D", "2960", "2964"),
    (SECTION_NON_CURRENT_ASSETS, "NcaShareIsAmort", "Share issue accumulated amortisation", "C", "2965", "2965"),
    (SECTION_NON_CURRENT_ASSETS, "NcaDebIs", "Debenture issue expenses", "D", "2966", "2968"),
    (SECTION_NON_CURRENT_ASSETS, "NcaDebIsAmort", "Debenture issue accumulated amortisation", "C", "2969", "2969"),
    (SECTION_NON_CURRENT_ASSETS, "NcaFITB", "Future income tax benefit", "D", "2970", "2974"),
    (SECTION_NON_CURRENT_ASSETS, "NcaResDev", "Research & development", "D", "2975", "2978"),
    (SECTION_NON_CURRENT_ASSETS, "NcaResDevAmort", "Research accumulated amortisation", "C", "2979", "2979"),
    (SECTION_NON_CURRENT_ASSETS, "NcaBorr", "Borrowing", "D", "2980", "2988"),
    (SECTION_NON_CURRENT_ASSETS, "NcaBorrAccDep", "Borrowing accumulated amortisation", "C", "2989", "2989"),
    (SECTION_NON_CURRENT_ASSETS, "NcaOther3", "Other", "D", "2990", "2998"),
    (SECTION_NON_CURRENT_ASSETS, "NcaInvestProperty", "Investment Property", "D", "2999", "2999"),

    # ======================================================================
    # Current Liabilities
    # ======================================================================
    (SECTION_CURRENT_LIABILITIES, "ClAll", "Current liabilities", "C", "3000", "3499"),
    (SECTION_CURRENT_LIABILITIES, "ClUnBank", "Unsecured - Bank loans", "C", "3000", "3047"),
    (SECTION_CURRENT_LIABILITIES, "ClUnTrade", "Unsecured - Trade creditor", "C", "3048", "3065"),
    (SECTION_CURRENT_LIABILITIES, "ClUnBills", "Unsecured - Bills & promissory notes", "C", "3066", "3083"),
    (SECTION_CURRENT_LIABILITIES, "ClUnOtherLoans", "Unsecured - Other loans", "C", "3084", "3099"),
    (SECTION_CURRENT_LIABILITIES, "ClUnOtherLoan", "Unsecured - Other loans", "C", "3100", "3100"),
    (SECTION_CURRENT_LIABILITIES, "ClUnUnexpInt", "Unsecured - Unexpired interest charges", "D", "3101", "3101"),
    (SECTION_CURRENT_LIABILITIES, "ClUnOtherCred", "Unsecured - Other creditor", "C", "3102", "3119"),
    (SECTION_CURRENT_LIABILITIES, "ClUnDeb", "Unsecured - Debentures", "C", "3120", "3137"),
    (SECTION_CURRENT_LIABILITIES, "ClUnLeaseLiab", "Unsecured - Lease liability", "C", "3138", "3154"),
    (SECTION_CURRENT_LIABILITIES, "ClUnTrustLiab", "Unsecured - Trust liability", "C", "3155", "3155"),
    (SECTION_CURRENT_LIABILITIES, "ClSecBankOdraft", "Secured - Bank overdraft", "C", "3156", "3173"),
    (SECTION_CURRENT_LIABILITIES, "ClSecBankLoan", "Secured - Bank loans", "C", "3174", "3191"),
    (SECTION_CURRENT_LIABILITIES, "ClSecTradeCr", "Secured - Trade creditor", "C", "3192", "3209"),
    (SECTION_CURRENT_LIABILITIES, "ClSecBills", "Secured - Bills & promissory notes", "C", "3210", "3227"),
    (SECTION_CURRENT_LIABILITIES, "ClSecOtherLoans1", "Secured - Other loans", "C", "3228", "3243"),
    (SECTION_CURRENT_LIABILITIES, "ClSecOtherLoans2", "Secured - Other loans", "C", "3244", "3244"),
    (SECTION_CURRENT_LIABILITIES, "ClSecUnexpInt", "Secured - Unexpired interest charges", "D", "3245", "3245"),
    (SECTION_CURRENT_LIABILITIES, "ClSecOtherCr", "Secured - Other creditor", "C", "3246", "3263"),
    (SECTION_CURRENT_LIABILITIES, "ClSecDeb", "Secured - Debentures", "C", "3264", "3281"),
    (SECTION_CURRENT_LIABILITIES, "ClSecLeaseLiab", "Secured - Lease liability", "C", "3282", "3298"),
    (SECTION_CURRENT_LIABILITIES, "ClSecTrustLiab", "Secured - Trust liability", "C", "3299", "3299"),
    (SECTION_CURRENT_LIABILITIES, "ClSecDiv", "Dividends", "C", "3300", "3324"),
    (SECTION_CURRENT_LIABILITIES, "ClTax", "Taxation", "C", "3325", "3349"),
    (SECTION_CURRENT_LIABILITIES, "ClEmpEnt", "Employee entitlements", "C", "3350", "3374"),
    (SECTION_CURRENT_LIABILITIES, "ClSecSundryProv", "Sundry provisions", "C", "3375", "3379"),
    (SECTION_CURRENT_LIABILITIES, "ClTrustProv", "Trust provisions", "C", "3399", "3399"),
    (SECTION_CURRENT_LIABILITIES, "ClAdvancePay", "Advance payments", "C", "3400", "3449"),
    (SECTION_CURRENT_LIABILITIES, "ClSundry", "Sundry", "C", "3450", "3498"),
    (SECTION_CURRENT_LIABILITIES, "ClTrustOther", "Trust - Other", "C", "3499", "3499"),
    (SECTION_CURRENT_LIABILITIES, "ClGST", "GST liability", "C", "3380", "3389"),
    (SECTION_CURRENT_LIABILITIES, "ClOtherTaxLiabs", "Other ATO liabilities", "C", "3390", "3398"),
    (SECTION_CURRENT_LIABILITIES, "ClTaxLiab", "Provision for tax", "C", "3325", "3329"),
    (SECTION_CURRENT_LIABILITIES, "ClDeferredTax", "Provision for deferred tax", "C", "3330", "3330"),

    # ======================================================================
    # Non-Current Liabilities
    # ======================================================================
    (SECTION_NON_CURRENT_LIABILITIES, "NclAll", "Non-Current Liabilities", "C", "3500", "3999"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclUnBank", "Unsecured - Bank loans", "C", "3500", "3522"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclUnOtherLoans", "Unsecured - Other loans", "C", "3523", "3523"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclUnUexpInt", "Unsecured - Unexpired interest charges", "D", "3524", "3524"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclUnLoanHC", "Unsecured - Loans, holding company", "C", "3525", "3544"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclUnLoanOtherCoy", "Unsecured - Loans, other companies", "C", "3545", "3564"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclUnOther", "Unsecured - Other loans", "C", "3565", "3584"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclUnDeb", "Unsecured - Debentures", "C", "3585", "3604"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclUnLeaseLiab", "Unsecured - Lease liability", "C", "3605", "3623"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclUnTrust", "Unsecured - Trust liability", "C", "3624", "3624"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclSecBankLoan", "Secured bank loans", "C", "3625", "3639"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclSecOtherLoan1", "Secured other loans", "C", "3640", "3648"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclSecUnexpInt", "Secured unexpired interest charges", "D", "3649", "3649"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclSecLoanHC", "Secured loans, holding company", "C", "3650", "3669"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclSecLoanOthCoy", "Secured loans, related companies", "C", "3670", "3689"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclSecOtherLoan2", "Secured other loans", "C", "3690", "3709"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclSecDeb", "Secured - Debentures", "C", "3710", "3719"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclSecLeaseLiab", "Secured lease liability", "C", "3720", "3748"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclSecTrustLiab", "Secured trust liability", "C", "3749", "3749"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclEmpEnt", "Employee entitlements", "C", "3750", "3839"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclDeferredTax", "Deferred income tax", "C", "3840", "3919"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclSundryProv", "Sundry provisions", "C", "3920", "3958"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclTrustProv", "Trust provisions", "C", "3959", "3959"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclOther", "Other", "C", "3960", "3998"),
    (SECTION_NON_CURRENT_LIABILITIES, "NclTrustOther", "Trust - Other", "C", "3999", "3999"),

    # ======================================================================
    # Capital Accounts
    # ======================================================================
    (SECTION_CAPITAL_ACCOUNTS, "CapAll", "Capital accounts", "C", "4000", "4099"),
    (SECTION_CAPITAL_ACCOUNTS, "CapOpBal", "Opening balance", "C", "4000", "4000"),
    (SECTION_CAPITAL_ACCOUNTS, "CapCred", "Capital credits", "C", "4001", "4050"),
    (SECTION_CAPITAL_ACCOUNTS, "CapProfShare", "Share of profit", "C", "4049", "4049"),
    (SECTION_CAPITAL_ACCOUNTS, "CapDeb", "Capital debits", "D", "4051", "4099"),

    # ======================================================================
    # P&L Appropriation
    # ======================================================================
    (SECTION_PL_APPROPRIATION, "AppnAll", "P & L appropriation", "D", "4100", "4198"),
    (SECTION_PL_APPROPRIATION, "AppnAb", "Abnormal items", "D", "4100", "4109"),
    (SECTION_PL_APPROPRIATION, "AppnTaxOpProfit", "Income tax, operating profit", "D", "4110", "4110"),
    (SECTION_PL_APPROPRIATION, "AppnProfExtra", "Profit, extraordinary", "C", "4111", "4119"),
    (SECTION_PL_APPROPRIATION, "AppnTaxExtra", "Income tax - Extraordinary", "D", "4120", "4120"),
    (SECTION_PL_APPROPRIATION, "AppnMinority", "Minority interests in operating profit & extraordinary", "D", "4121", "4129"),
    (SECTION_PL_APPROPRIATION, "AppnAdj", "Adjustments", "C", "4130", "4139"),
    (SECTION_PL_APPROPRIATION, "AppnTransFr", "Transfers from reserves", "C", "4140", "4159"),
    (SECTION_PL_APPROPRIATION, "AppnDiv", "Dividend provided for or paid", "D", "4160", "4169"),
    (SECTION_PL_APPROPRIATION, "AppnTransTo", "Transfers to reserves", "D", "4170", "4179"),
    (SECTION_PL_APPROPRIATION, "AppnOther", "Other appropriations", "D", "4180", "4198"),
    (SECTION_PL_APPROPRIATION, "RetainedProfit", "Retained profits", "C", "4199", "4199"),
    (SECTION_PL_APPROPRIATION, "AppnOverProv", "Over-provision for taxation", "C", "4135", "4135"),
    (SECTION_PL_APPROPRIATION, "AppnUnderProv", "Under-provision for taxation", "C", "4190", "4190"),

    # ======================================================================
    # Equity / Trust-Specific
    # ======================================================================
    (SECTION_EQUITY_TRUST, "TCont", "Contribution by settlor", "C", "4200", "4229"),
    (SECTION_EQUITY_TRUST, "TSubUnits", "Subscribed units", "C", "4230", "4259"),
    (SECTION_EQUITY_TRUST, "TGifts", "Gifts to trust", "C", "4260", "4299"),
    (SECTION_EQUITY_TRUST, "EqReserves", "Reserves", "C", "4300", "4399"),
    (SECTION_EQUITY_TRUST, "EqAssetReval", "Assets revaluation reserve", "C", "4375", "4375"),
    (SECTION_EQUITY_TRUST, "EqGeneral", "General reserve", "C", "4380", "4380"),
    (SECTION_EQUITY_TRUST, "TCap", "Trust capital accounts", "C", "4200", "4599"),
    (SECTION_EQUITY_TRUST, "EqCapitalReserves", "Capital reserves", "C", "4350", "4350"),
    (SECTION_EQUITY_TRUST, "UPEAll", "Unpaid present entitlements account", "C", "4400", "4499"),
    (SECTION_EQUITY_TRUST, "UPEOpBal", "UPE opening balance", "C", "4400", "4400"),
    (SECTION_EQUITY_TRUST, "UPECred", "UPE credits", "C", "4401", "4450"),
    (SECTION_EQUITY_TRUST, "UPEProfShare", "Share of profit", "C", "4449", "4449"),
    (SECTION_EQUITY_TRUST, "UPEDeb", "UPE debits", "D", "4451", "4499"),
    (SECTION_EQUITY_TRUST, "SubTAll", "Sub-trust accounts", "C", "4500", "4599"),
    (SECTION_EQUITY_TRUST, "SubTOpBal", "Sub-trust opening balance", "C", "4500", "4500"),
    (SECTION_EQUITY_TRUST, "SubTCred", "Sub-trust credits", "C", "4501", "4550"),
    (SECTION_EQUITY_TRUST, "SubTProfShare", "Share of profit", "C", "4549", "4549"),
    (SECTION_EQUITY_TRUST, "SubTDeb", "Sub-trust debits", "D", "4551", "4599"),
]
