"""Views for Legal Document Generation — wizard, rendering, FuseSign integration."""
import io
import json
import logging
import os
import subprocess
import tempfile
import uuid

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import FileResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.views.decorators.http import require_POST

from core.models import (
    Entity,
    EntityOfficer,
    FinancialYear,
    GoverningDocument,
    LegalDocument,
    LegalDocumentTemplate,
)

logger = logging.getLogger(__name__)

# Standard disclaimer appended to every generated document
STANDARD_DISCLAIMER = (
    "This document has been generated by StatementHub on behalf of MC & S Chartered "
    "Accountants. It is based on the information provided and the applicable template. "
    "MC & S recommends that all legal documents be reviewed by a qualified solicitor "
    "before execution. MC & S accepts no liability for any loss arising from the use "
    "of this document without independent legal advice."
)


# ---------------------------------------------------------------------------
# Template Management (Admin)
# ---------------------------------------------------------------------------
@login_required
def legal_template_list(request):
    """List all legal document templates."""
    templates = LegalDocumentTemplate.objects.filter(is_active=True).order_by("name")
    return render(request, "core/legal/template_list.html", {
        "templates": templates,
    })


@login_required
@require_POST
def legal_template_upload(request):
    """Upload a new legal document template."""
    name = request.POST.get("name", "")
    doc_type = request.POST.get("document_type", "")
    entity_types = request.POST.getlist("entity_types")
    file = request.FILES.get("template_file")

    if not file or not doc_type:
        return JsonResponse({"error": "File and document type are required."}, status=400)

    # Check if template already exists for this type
    existing = LegalDocumentTemplate.objects.filter(
        document_type=doc_type, is_active=True
    ).first()

    if existing:
        # Version up
        existing.is_active = False
        existing.save(update_fields=["is_active"])
        version = existing.version + 1
    else:
        version = 1

    template = LegalDocumentTemplate.objects.create(
        name=name or dict(LegalDocumentTemplate.DocumentType.choices).get(doc_type, doc_type),
        document_type=doc_type,
        entity_types=entity_types,
        template_file=file,
        version=version,
        created_by=request.user,
    )

    # Extract variable schema from template
    try:
        schema = _extract_template_variables(template)
        template.variable_schema = schema
        template.save(update_fields=["variable_schema"])
    except Exception as e:
        logger.warning("Failed to extract template variables: %s", e)

    return JsonResponse({"status": "ok", "template_id": str(template.pk)})


# ---------------------------------------------------------------------------
# Document Generation Wizard
# ---------------------------------------------------------------------------
@login_required
def legal_doc_wizard(request, pk, doc_type):
    """
    Document generation wizard.
    Step 1: Load entity context + template variables
    Step 2: User fills in wizard form
    Step 3: Generate document
    """
    fy = get_object_or_404(FinancialYear, pk=pk)
    entity = fy.entity

    template = LegalDocumentTemplate.objects.filter(
        document_type=doc_type, is_active=True
    ).first()

    if not template:
        return render(request, "core/legal/wizard.html", {
            "fy": fy,
            "entity": entity,
            "error": f"No active template found for document type: {doc_type}",
        })

    # Build pre-populated context from entity data
    context = _build_entity_context(entity, fy)

    # Get governing document text for Eva context
    governing_doc = entity.governing_documents.filter(
        is_primary=True, status="active",
        extraction_status__in=["completed", "completed_with_warnings"],
    ).first()

    return render(request, "core/legal/wizard.html", {
        "fy": fy,
        "entity": entity,
        "template": template,
        "doc_type": doc_type,
        "pre_populated": context,
        "variable_schema": template.variable_schema,
        "governing_doc": governing_doc,
        "disclaimer": STANDARD_DISCLAIMER,
    })


@login_required
@require_POST
def legal_doc_generate(request, pk, doc_type):
    """Generate a legal document from template + wizard inputs."""
    fy = get_object_or_404(FinancialYear, pk=pk)
    entity = fy.entity

    template = LegalDocumentTemplate.objects.filter(
        document_type=doc_type, is_active=True
    ).first()

    if not template:
        return JsonResponse({"error": "No active template found."}, status=404)

    # Merge entity context with user-provided parameters
    parameters = json.loads(request.body) if request.content_type == "application/json" else request.POST.dict()
    entity_context = _build_entity_context(entity, fy)
    entity_context.update(parameters)

    # Add standard fields
    entity_context["disclaimer"] = STANDARD_DISCLAIMER
    entity_context["generation_date"] = timezone.now().strftime("%d %B %Y")
    entity_context["firm_name"] = "MC & S Chartered Accountants"

    try:
        # Step 1: Render docx from template
        docx_bytes = _render_template(template, entity_context)

        # Step 2: Convert to PDF via LibreOffice
        pdf_bytes = _convert_to_pdf(docx_bytes)

        # Step 3: Save to database
        doc = LegalDocument.objects.create(
            entity=entity,
            financial_year=fy,
            template=template,
            document_type=doc_type,
            parameters=parameters,
            generated_by=request.user,
            disclaimer_acknowledged=parameters.get("disclaimer_acknowledged", False),
            disclaimer_acknowledged_at=timezone.now() if parameters.get("disclaimer_acknowledged") else None,
        )

        # Save files
        from django.core.files.base import ContentFile
        doc_filename = f"{entity.name}_{doc_type}_{fy.end_date.year}.docx"
        doc.generated_file.save(doc_filename, ContentFile(docx_bytes))

        if pdf_bytes:
            pdf_filename = f"{entity.name}_{doc_type}_{fy.end_date.year}.pdf"
            doc.pdf_file.save(pdf_filename, ContentFile(pdf_bytes))

        return JsonResponse({
            "status": "ok",
            "document_id": str(doc.pk),
            "docx_url": doc.generated_file.url if doc.generated_file else None,
            "pdf_url": doc.pdf_file.url if doc.pdf_file else None,
        })

    except Exception as e:
        logger.exception("Document generation failed: %s", e)
        return JsonResponse({"error": str(e)}, status=500)


# ---------------------------------------------------------------------------
# Document Download
# ---------------------------------------------------------------------------
@login_required
def legal_doc_download(request, doc_pk, fmt="docx"):
    """Download a generated legal document."""
    doc = get_object_or_404(LegalDocument, pk=doc_pk)

    if fmt == "pdf" and doc.pdf_file:
        return FileResponse(doc.pdf_file.open(), content_type="application/pdf",
                            as_attachment=True, filename=os.path.basename(doc.pdf_file.name))
    elif doc.generated_file:
        return FileResponse(
            doc.generated_file.open(),
            content_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            as_attachment=True,
            filename=os.path.basename(doc.generated_file.name),
        )
    else:
        return JsonResponse({"error": "File not found."}, status=404)


# ---------------------------------------------------------------------------
# Document List (per FY)
# ---------------------------------------------------------------------------
@login_required
def legal_doc_list(request, pk):
    """List all generated legal documents for a financial year."""
    fy = get_object_or_404(FinancialYear, pk=pk)
    documents = LegalDocument.objects.filter(financial_year=fy).order_by("-generated_at")
    return JsonResponse({
        "documents": [
            {
                "id": str(d.pk),
                "document_type": d.document_type,
                "document_type_display": d.get_document_type_display(),
                "status": d.status,
                "version": d.version,
                "generated_at": d.generated_at.isoformat(),
                "generated_by": d.generated_by.get_full_name() if d.generated_by else "",
                "docx_url": d.generated_file.url if d.generated_file else None,
                "pdf_url": d.pdf_file.url if d.pdf_file else None,
                "fusesign_status": d.fusesign_status,
            }
            for d in documents
        ]
    })


# ---------------------------------------------------------------------------
# FuseSign Integration
# ---------------------------------------------------------------------------
@login_required
@require_POST
def legal_doc_send_fusesign(request, doc_pk):
    """Send a generated document to FuseSign for electronic signing."""
    doc = get_object_or_404(LegalDocument, pk=doc_pk)

    if not doc.pdf_file:
        return JsonResponse({"error": "PDF file required for FuseSign."}, status=400)

    fusesign_api_key = getattr(settings, "FUSESIGN_API_KEY", "")
    fusesign_base_url = getattr(settings, "FUSESIGN_BASE_URL", "")

    if not fusesign_api_key or not fusesign_base_url:
        return JsonResponse(
            {"error": "FuseSign is not configured. Set FUSESIGN_API_KEY and FUSESIGN_BASE_URL in settings."},
            status=400,
        )

    try:
        import requests as http_requests

        # Get signatories from entity officers
        signatories = _get_signatories(doc.entity)
        if not signatories:
            return JsonResponse({"error": "No signatories found for this entity."}, status=400)

        # Create FuseSign envelope
        payload = {
            "title": f"{doc.get_document_type_display()} — {doc.entity.name}",
            "message": f"Please review and sign the attached {doc.get_document_type_display()}.",
            "signers": [
                {
                    "name": s["name"],
                    "email": s["email"],
                    "order": idx + 1,
                }
                for idx, s in enumerate(signatories)
            ],
        }

        # Upload document
        headers = {
            "Authorization": f"Bearer {fusesign_api_key}",
        }

        resp = http_requests.post(
            f"{fusesign_base_url}/api/v1/envelopes",
            json=payload,
            headers=headers,
            timeout=30,
        )
        resp.raise_for_status()
        envelope_data = resp.json()

        # Upload the PDF to the envelope
        doc.pdf_file.seek(0)
        files_resp = http_requests.post(
            f"{fusesign_base_url}/api/v1/envelopes/{envelope_data['id']}/documents",
            files={"file": (os.path.basename(doc.pdf_file.name), doc.pdf_file.read(), "application/pdf")},
            headers=headers,
            timeout=60,
        )
        files_resp.raise_for_status()

        # Send the envelope
        send_resp = http_requests.post(
            f"{fusesign_base_url}/api/v1/envelopes/{envelope_data['id']}/send",
            headers=headers,
            timeout=30,
        )
        send_resp.raise_for_status()

        doc.fusesign_envelope_id = envelope_data["id"]
        doc.fusesign_status = LegalDocument.FuseSignStatus.SENT
        doc.save(update_fields=["fusesign_envelope_id", "fusesign_status"])

        return JsonResponse({
            "status": "ok",
            "envelope_id": envelope_data["id"],
            "message": f"Document sent to {len(signatories)} signer(s) via FuseSign.",
        })

    except Exception as e:
        logger.exception("FuseSign send failed: %s", e)
        return JsonResponse({"error": str(e)}, status=500)


# ---------------------------------------------------------------------------
# Internal Helpers
# ---------------------------------------------------------------------------
def _build_entity_context(entity, fy):
    """Build a template context dict from entity and FY data."""
    officers = EntityOfficer.objects.filter(entity=entity, is_active=True)
    directors = officers.filter(role__in=["director", "sole_director"])
    shareholders = officers.filter(role__in=["shareholder", "director"])

    context = {
        # Entity
        "entity_name": entity.name,
        "entity_type": entity.get_entity_type_display() if hasattr(entity, "get_entity_type_display") else entity.entity_type,
        "abn": entity.abn or "",
        "acn": entity.acn or "",
        "tfn": entity.tfn or "",
        "registered_address": entity.registered_address or "",
        "principal_place_of_business": entity.principal_place_of_business or "",
        "state_of_registration": entity.state_of_registration or "",
        "date_of_incorporation": entity.date_of_incorporation.strftime("%d %B %Y") if entity.date_of_incorporation else "",
        # Financial Year
        "fy_start_date": fy.start_date.strftime("%d %B %Y"),
        "fy_end_date": fy.end_date.strftime("%d %B %Y"),
        "fy_year": str(fy.end_date.year),
        "fy_label": f"{fy.start_date.strftime('%d %B %Y')} to {fy.end_date.strftime('%d %B %Y')}",
        # Officers
        "directors": [
            {
                "name": o.name,
                "role": o.get_role_display() if hasattr(o, "get_role_display") else o.role,
                "date_appointed": o.date_appointed.strftime("%d %B %Y") if o.date_appointed else "",
                "shares_held": str(o.shares_held) if hasattr(o, "shares_held") and o.shares_held else "",
            }
            for o in directors
        ],
        "shareholders": [
            {
                "name": o.name,
                "shares_held": str(o.shares_held) if hasattr(o, "shares_held") and o.shares_held else "",
            }
            for o in shareholders
        ],
        "all_officers": [
            {"name": o.name, "role": o.get_role_display() if hasattr(o, "get_role_display") else o.role}
            for o in officers
        ],
        # Trust-specific
        "trustee_name": entity.trustee_acn or "",
        "deed_date": entity.deed_date.strftime("%d %B %Y") if hasattr(entity, "deed_date") and entity.deed_date else "",
        "vesting_date": entity.vesting_date.strftime("%d %B %Y") if hasattr(entity, "vesting_date") and entity.vesting_date else "",
        # Company-specific
        "total_shares_on_issue": str(entity.total_shares_on_issue) if hasattr(entity, "total_shares_on_issue") and entity.total_shares_on_issue else "",
        "is_large_proprietary": getattr(entity, "is_large_proprietary", False),
    }

    return context


def _extract_template_variables(template):
    """Extract {{variable}} placeholders from a docxtpl template."""
    import re
    try:
        from docxtpl import DocxTemplate
        tpl = DocxTemplate(template.template_file.path)
        # Get the XML content
        xml_content = tpl.get_xml()
        # Find all {{variable}} patterns
        variables = set(re.findall(r'\{\{([\w.]+)\}\}', xml_content))
        # Also find {% for %} loop variables
        loops = re.findall(r'\{%\s*for\s+(\w+)\s+in\s+(\w+)\s*%\}', xml_content)

        schema = {
            "variables": sorted(variables),
            "loops": [{"item": l[0], "collection": l[1]} for l in loops],
        }
        return schema
    except Exception as e:
        logger.warning("Failed to extract template variables: %s", e)
        return {"variables": [], "loops": []}


def _render_template(template, context):
    """Render a docxtpl template with the given context and return bytes."""
    from docxtpl import DocxTemplate

    tpl = DocxTemplate(template.template_file.path)
    tpl.render(context)

    buffer = io.BytesIO()
    tpl.save(buffer)
    return buffer.getvalue()


def _convert_to_pdf(docx_bytes):
    """Convert DOCX bytes to PDF using LibreOffice."""
    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            docx_path = os.path.join(tmpdir, "document.docx")
            with open(docx_path, "wb") as f:
                f.write(docx_bytes)

            result = subprocess.run(
                [
                    "libreoffice",
                    "--headless",
                    "--convert-to", "pdf",
                    "--outdir", tmpdir,
                    docx_path,
                ],
                capture_output=True,
                timeout=60,
            )

            pdf_path = os.path.join(tmpdir, "document.pdf")
            if os.path.exists(pdf_path):
                with open(pdf_path, "rb") as f:
                    return f.read()
            else:
                logger.warning("LibreOffice PDF conversion failed: %s", result.stderr.decode())
                return None
    except FileNotFoundError:
        logger.warning("LibreOffice not installed — skipping PDF conversion")
        return None
    except Exception as e:
        logger.warning("PDF conversion failed: %s", e)
        return None


def _get_signatories(entity):
    """Get signatories for FuseSign from entity officers."""
    officers = EntityOfficer.objects.filter(
        entity=entity,
        is_active=True,
        role__in=["director", "sole_director", "trustee"],
    )
    signatories = []
    for o in officers:
        email = getattr(o, "email", "") or ""
        if email:
            signatories.append({"name": o.name, "email": email})
    return signatories
