"""
Views for Legal Document Generation — wizard, rendering, FuseSign integration.

Document Types:
  1. Division 7A Loan Agreement
  2. Change of Trustee Set (3 documents)
  3. Fixed Unit Trust Deed + Ancillaries (5 documents)
  4. Unit Transfer Package (7 documents)
"""
import io
import json
import logging
import os
import subprocess
import tempfile
import uuid

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import FileResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.views.decorators.http import require_POST

from config.authorization import get_entity_for_user, get_financial_year_for_user
from core.models import (
    Entity,
    EntityOfficer,
    EntityRelationship,
    FinancialYear,
    GoverningDocument,
    LegalDocument,
    LegalDocumentTemplate,
    RiskFlag,
)

from core.legal_doc_contexts import (
    build_change_of_trustee_context,
    build_div7a_context,
    build_fixed_unit_trust_context,
    build_unit_transfer_context,
    get_change_of_trustee_signatories,
    get_div7a_signatories,
    get_fixed_unit_trust_signatories,
    get_unit_transfer_signatories,
    validate_fixed_unit_trust,
    _get_directors_for_entity,
    _get_entity_address,
)

from core.legal_doc_service import (
    log_fusesign_activity,
    render_and_create_document,
    render_multi_document_set,
)

logger = logging.getLogger(__name__)

def _get_standard_disclaimer():
    """Return the standard disclaimer, using FirmSettings firm name if available."""
    try:
        from core.models import FirmSettings
        fs = FirmSettings.get()
        if fs.document_disclaimer:
            return fs.document_disclaimer
        name = fs.firm_name or "MC & S Chartered Accountants"
    except Exception:
        name = "MC & S Chartered Accountants"
    return (
        f"This document has been generated by StatementHub on behalf of {name}. "
        "It is based on the information provided and the applicable template. "
        f"{name} recommends that all legal documents be reviewed by a qualified solicitor "
        f"before execution. {name} accepts no liability for any loss arising from the use "
        "of this document without independent legal advice."
    )


# Lazy wrapper so module-level references still work
class _LazyDisclaimer:
    def __str__(self):
        return _get_standard_disclaimer()
    def __add__(self, other):
        return str(self) + other
    def __radd__(self, other):
        return other + str(self)


STANDARD_DISCLAIMER = _LazyDisclaimer()


# ---------------------------------------------------------------------------
# Template Management (Admin)
# ---------------------------------------------------------------------------
@login_required
def legal_template_list(request):
    """List all legal document templates."""
    templates = LegalDocumentTemplate.objects.filter(is_active=True).order_by("name")
    return render(request, "core/legal/template_list.html", {
        "templates": templates,
    })


@login_required
@require_POST
def legal_template_upload(request):
    """Upload a new legal document template."""
    name = request.POST.get("name", "")
    doc_type = request.POST.get("document_type", "")
    entity_types = request.POST.getlist("entity_types")
    file = request.FILES.get("template_file")

    if not file or not doc_type:
        return JsonResponse({"error": "File and document type are required."}, status=400)

    # Check if template already exists for this type
    existing = LegalDocumentTemplate.objects.filter(
        document_type=doc_type, is_active=True
    ).first()

    if existing:
        # Version up
        existing.is_active = False
        existing.save(update_fields=["is_active"])
        version = existing.version + 1
    else:
        version = 1

    template = LegalDocumentTemplate.objects.create(
        name=name or dict(LegalDocumentTemplate.DocumentType.choices).get(doc_type, doc_type),
        document_type=doc_type,
        entity_types=entity_types,
        template_file=file,
        version=version,
        created_by=request.user,
    )

    # Extract variable schema from template
    try:
        schema = _extract_template_variables(template)
        template.variable_schema = schema
        template.save(update_fields=["variable_schema"])
    except Exception as e:
        logger.warning("Failed to extract template variables: %s", e)

    return JsonResponse({"status": "ok", "template_id": str(template.pk)})


# ---------------------------------------------------------------------------
# Download existing legal document template file
# ---------------------------------------------------------------------------
@login_required
def legal_template_download(request, pk):
    """Download the .docx file for a LegalDocumentTemplate."""
    if not request.user.is_admin:
        from django.http import HttpResponseForbidden
        return HttpResponseForbidden("Admin access required.")
    template = get_object_or_404(LegalDocumentTemplate, pk=pk)
    if not template.template_file:
        from django.http import HttpResponseNotFound
        return HttpResponseNotFound("No file attached to this template.")
    safe_name = f"{template.name.replace(' ', '_')}_v{template.version}.docx"
    try:
        file_data = template.template_file.read()
    except Exception as e:
        logger.error("Failed to read template file: %s", e)
        from django.http import HttpResponseServerError
        return HttpResponseServerError(f"Could not read template file: {e}")
    from django.http import HttpResponse
    response = HttpResponse(
        file_data,
        content_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    )
    response["Content-Disposition"] = f'attachment; filename="{safe_name}"'
    return response


# ---------------------------------------------------------------------------
# Replace (upload new version of) a legal document template
# ---------------------------------------------------------------------------
@login_required
@require_POST
def legal_template_replace(request, pk):
    """Upload a replacement .docx file for an existing LegalDocumentTemplate."""
    if not request.user.is_admin:
        return JsonResponse({"error": "Admin access required."}, status=403)
    template = get_object_or_404(LegalDocumentTemplate, pk=pk)
    file = request.FILES.get("template_file")
    if not file:
        return JsonResponse({"error": "No file uploaded."}, status=400)
    if not file.name.lower().endswith(".docx"):
        return JsonResponse({"error": "Only .docx files are accepted."}, status=400)
    # Deactivate the current version
    template.is_active = False
    template.save(update_fields=["is_active"])
    # Create the new version
    new_template = LegalDocumentTemplate.objects.create(
        name=template.name,
        document_type=template.document_type,
        entity_types=template.entity_types,
        template_file=file,
        version=template.version + 1,
        is_active=True,
        solicitor_approved=False,
        variable_schema=template.variable_schema,
        created_by=request.user,
    )
    # Re-extract variable schema from the new file
    try:
        schema = _extract_template_variables(new_template)
        new_template.variable_schema = schema
        new_template.save(update_fields=["variable_schema"])
    except Exception as e:
        logger.warning("Failed to extract template variables from replacement: %s", e)
    from core.views import _log_action
    _log_action(
        request, "update",
        f"Replaced legal template '{template.name}' — now v{new_template.version}",
    )
    return JsonResponse({
        "status": "ok",
        "template_id": str(new_template.pk),
        "version": new_template.version,
        "message": f"Template replaced successfully. Now at version {new_template.version}.",
    })


# ---------------------------------------------------------------------------
# Generic Document Generation Wizard (fallback for non-specific types)
# ---------------------------------------------------------------------------
@login_required
def legal_doc_wizard(request, pk, doc_type):
    """
    Generic document generation wizard.
    Routes to document-type-specific wizards when available.
    """
    fy = get_financial_year_for_user(request, pk)
    entity = fy.entity

    # Route to specific wizards
    SPECIFIC_WIZARDS = {
        "div7a_loan_agreement": div7a_wizard,
        "trust_deed_change_trustee": change_of_trustee_wizard,
        "unit_trust_deed": fixed_unit_trust_wizard,
        "unit_transfer": unit_transfer_wizard,
    }

    specific_view = SPECIFIC_WIZARDS.get(doc_type)
    if specific_view:
        return specific_view(request, pk)

    # Fall back to generic wizard
    template = LegalDocumentTemplate.objects.filter(
        document_type=doc_type, is_active=True
    ).first()

    if not template:
        return render(request, "core/legal/wizard.html", {
            "fy": fy,
            "entity": entity,
            "error": f"No active template found for document type: {doc_type}",
        })

    # Build pre-populated context from entity data
    context = _build_entity_context(entity, fy)

    # Get governing document text for Eva context
    governing_doc = entity.governing_documents.filter(
        is_primary=True, status="active",
        extraction_status__in=["completed", "completed_with_warnings"],
    ).first()

    return render(request, "core/legal/wizard.html", {
        "fy": fy,
        "entity": entity,
        "template": template,
        "doc_type": doc_type,
        "pre_populated": context,
        "variable_schema": template.variable_schema or {"variables": [], "loops": []},
        "governing_doc": governing_doc,
        "disclaimer": STANDARD_DISCLAIMER,
    })


@login_required
@require_POST
def engagement_letter_generate(request, pk):
    """Generate engagement letter via DocumentContextBuilder for correct selected_services."""
    entity = get_entity_for_user(request, pk)

    params = json.loads(request.body) if request.content_type == "application/json" else request.POST.dict()

    financial_year_id = params.get("financial_year_id")
    fy = get_object_or_404(FinancialYear, pk=financial_year_id, entity=entity) if financial_year_id else None

    template = LegalDocumentTemplate.objects.filter(
        document_type="engagement_letter", is_active=True
    ).first()
    if not template:
        return JsonResponse({"error": "No active engagement letter template."}, status=404)

    _logger = logging.getLogger(__name__)
    _logger.info("EL wizard_data: %s", params)

    from core.document_context_builder import DocumentContextBuilder
    dcb = DocumentContextBuilder(entity, financial_year=fy, wizard_data=params)
    context = dcb.build("engagement_letter")
    _logger.info("EL context selected_services: %s", context.get('selected_services'))

    result = render_and_create_document(
        entity=entity,
        financial_year=fy,
        template=template,
        doc_type="engagement_letter",
        context=context,
        params=params,
        user=request.user,
        disclaimer_acknowledged=params.get("disclaimer_acknowledged", False),
    )

    if result.get("status") == "ok":
        # Save sanitised context_data for re-rendering
        from core.views_partnership_docs import _sanitise_context_for_storage
        doc_id = result.get("document_id")
        if doc_id:
            LegalDocument.objects.filter(pk=doc_id).update(
                context_data=_sanitise_context_for_storage(context)
            )
        return JsonResponse({
            "status": "ok",
            "document_id": result.get("document_id"),
            "docx_url": result.get("docx_url"),
            "pdf_url": result.get("pdf_url"),
            "message": "Engagement letter saved successfully.",
            "redirect_url": None,
        })
    return JsonResponse({"error": result.get("error", "Generation failed.")}, status=500)


@login_required
@require_POST
def legal_doc_generate(request, pk, doc_type):
    """
    Generate a legal document from template + wizard inputs.
    Routes to document-type-specific generators when available.
    """
    fy = get_financial_year_for_user(request, pk)
    entity = fy.entity

    # Route to specific generators
    SPECIFIC_GENERATORS = {
        "engagement_letter": engagement_letter_generate,
        "div7a_loan_agreement": div7a_generate,
        "trust_deed_change_trustee": change_of_trustee_generate,
        "unit_trust_deed": fixed_unit_trust_generate,
        "unit_transfer": unit_transfer_generate,
    }

    specific_view = SPECIFIC_GENERATORS.get(doc_type)
    if specific_view:
        return specific_view(request, pk)

    # Fall back to generic generation
    template = LegalDocumentTemplate.objects.filter(
        document_type=doc_type, is_active=True
    ).first()

    if not template:
        return JsonResponse({"error": "No active template found."}, status=404)

    # Merge entity context with user-provided parameters
    parameters = json.loads(request.body) if request.content_type == "application/json" else request.POST.dict()
    entity_context = _build_entity_context(entity, fy)
    entity_context.update(parameters)

    # Add standard fields
    entity_context["disclaimer"] = STANDARD_DISCLAIMER
    entity_context["generation_date"] = timezone.now().strftime("%d %B %Y")
    # Firm branding from FirmSettings (white-label support)
    try:
        from core.models import FirmSettings
        _fs = FirmSettings.get()
        entity_context["firm_name"] = _fs.firm_name or "MC & S Chartered Accountants"
        entity_context["firm_logo_url"] = _fs.logo_url or ""
        entity_context.setdefault("firm_address_1", _fs.firm_address_1 or "")
        entity_context.setdefault("firm_address_2", _fs.firm_address_2 or "")
        entity_context.setdefault("firm_phone", _fs.firm_phone or "")
        entity_context.setdefault("firm_email", _fs.firm_email or "")
    except Exception:
        entity_context["firm_name"] = "MC & S Chartered Accountants"
        entity_context["firm_logo_url"] = ""

    result = render_and_create_document(
        entity=entity,
        financial_year=fy,
        template=template,
        doc_type=doc_type,
        context=entity_context,
        params=parameters,
        user=request.user,
        disclaimer_acknowledged=parameters.get("disclaimer_acknowledged", False),
    )

    if result["status"] == "ok":
        return JsonResponse(result)
    else:
        return JsonResponse({"error": result.get("error", "Generation failed.")}, status=500)


# ===========================================================================
# DOCUMENT 1: Division 7A Loan Agreement
# ===========================================================================

@login_required
def div7a_wizard(request, pk):
    """
    Division 7A Loan Agreement wizard.

    Wizard fields:
      1. Borrower type (individual / trust / company) — conditional branch
      2. Borrower entity picker (for trust/company) or name (for individual)
      3. Agreement date
      4. Loan security type (secured / unsecured)

    Pre-populated from Risk Engine flag (if navigated from risk flag):
      - Loan amount (from debit balance)
      - Account code and name
    """
    fy = get_financial_year_for_user(request, pk)
    entity = fy.entity

    template = LegalDocumentTemplate.objects.filter(
        document_type="div7a_loan_agreement", is_active=True
    ).first()

    if not template:
        return render(request, "core/legal/div7a_wizard.html", {
            "fy": fy,
            "entity": entity,
            "error": "No active Division 7A Loan Agreement template found. Upload one in Legal Templates.",
        })

    # Check for risk flag pre-population
    risk_flag_id = request.GET.get("risk_flag")
    risk_flag_data = {}
    if risk_flag_id:
        try:
            flag = RiskFlag.objects.get(pk=risk_flag_id, financial_year=fy)
            risk_flag_data = {
                "loan_amount": flag.calculated_values.get("debit_balance", ""),
                "account_code": flag.calculated_values.get("account_code", ""),
                "account_name": flag.calculated_values.get("account_name", ""),
                "risk_flag_id": str(flag.pk),
            }
        except RiskFlag.DoesNotExist:
            pass

    # Get related entities for borrower picker (same client group)
    related_entities = Entity.objects.filter(
        client=entity.client
    ).exclude(pk=entity.pk).order_by("entity_name") if entity.client else Entity.objects.none()

    # Also get entities linked via EntityRelationship
    linked_entity_ids = EntityRelationship.objects.filter(
        Q(from_entity=entity) | Q(to_entity=entity)
    ).values_list("from_entity_id", "to_entity_id")
    linked_ids = set()
    for from_id, to_id in linked_entity_ids:
        linked_ids.add(from_id)
        linked_ids.add(to_id)
    linked_ids.discard(entity.pk)

    linked_entities = Entity.objects.filter(pk__in=linked_ids).order_by("entity_name")
    # Combine and deduplicate
    all_related = list(related_entities) + [e for e in linked_entities if e not in related_entities]

    # Get officers for individual borrower picker
    officers = EntityOfficer.objects.filter(
        entity=entity,
        date_ceased__isnull=True,
    ).filter(
        Q(role__in=["director", "shareholder", "director_shareholder"]) |
        Q(roles__overlap=["director", "shareholder"])
    ).order_by("full_name")

    # Get governing document
    governing_doc = entity.governing_documents.filter(
        is_primary=True, status="active",
        extraction_status__in=["completed", "completed_with_warnings"],
    ).first()

    return render(request, "core/legal/div7a_wizard.html", {
        "fy": fy,
        "entity": entity,
        "template": template,
        "risk_flag_data": risk_flag_data,
        "related_entities": all_related,
        "officers": officers,
        "governing_doc": governing_doc,
        "disclaimer": STANDARD_DISCLAIMER,
    })


@login_required
@require_POST
def div7a_generate(request, pk):
    """Generate Division 7A Loan Agreement."""
    fy = get_financial_year_for_user(request, pk)
    entity = fy.entity

    template = LegalDocumentTemplate.objects.filter(
        document_type="div7a_loan_agreement", is_active=True
    ).first()
    if not template:
        return JsonResponse({"error": "No active Div 7A template found."}, status=404)

    # Parse wizard parameters
    if request.content_type == "application/json":
        params = json.loads(request.body)
    else:
        params = request.POST.dict()

    # Build context
    context = build_div7a_context(entity, fy, params)

    # Enrich with DocumentContextBuilder (practice_* namespace + Jinja2 filters)
    try:
        from core.document_context_builder import DocumentContextBuilder
        dcb = DocumentContextBuilder(entity, financial_year=fy, wizard_data=params)
        enriched = dcb.build("div7a_loan_agreement")
        for k, v in enriched.items():
            if k not in context or k.startswith("practice_"):
                context[k] = v
    except Exception as _e:
        logger.warning("DCB enrichment skipped for div7a: %s", _e)

    # Generate document
    result = render_and_create_document(
        entity=entity,
        financial_year=fy,
        template=template,
        doc_type="div7a_loan_agreement",
        context=context,
        params=params,
        user=request.user,
        disclaimer_acknowledged=params.get("disclaimer_acknowledged", False),
    )

    # If generated from a risk flag, auto-resolve it
    risk_flag_id = params.get("risk_flag_id")
    if risk_flag_id and result.get("status") == "ok":
        try:
            flag = RiskFlag.objects.get(pk=risk_flag_id, financial_year=fy)
            if flag.status in ("open", "reviewed"):
                flag.status = "auto_resolved"
                flag.resolution_notes = (
                    f"Auto-resolved: Division 7A Loan Agreement generated "
                    f"(Document ID: {result['document_id']})"
                )
                flag.resolved_by = request.user
                flag.resolved_at = timezone.now()
                flag.save()
        except RiskFlag.DoesNotExist:
            pass

    if result["status"] == "ok":
        return JsonResponse(result)
    else:
        return JsonResponse({"error": result.get("error", "Generation failed.")}, status=500)


# ===========================================================================
# DOCUMENT 2: Change of Trustee Set
# ===========================================================================

@login_required
def change_of_trustee_wizard(request, pk):
    """
    Change of Trustee wizard — generates 3 documents:
      1. Deed of Change of Trustee
      2. Outgoing Trustee Director Resolution
      3. New Trustee Director Resolution (Minutes)

    Wizard fields:
      1. Outgoing trustee entity picker (pre-populated from trust's current trustee)
      2. New trustee entity picker
      3. Effective date
      4. Reason for change (optional)
      5. Appointment/retirement clause refs (Eva pre-populated)
    """
    fy = get_financial_year_for_user(request, pk)
    entity = fy.entity

    if entity.entity_type != "trust":
        return render(request, "core/legal/change_trustee_wizard.html", {
            "fy": fy,
            "entity": entity,
            "error": "Change of Trustee is only applicable to Trust entities.",
        })

    # Check for templates (need 3: deed, outgoing resolution, new trustee minutes)
    deed_template = LegalDocumentTemplate.objects.filter(
        document_type="trust_deed_change_trustee", is_active=True
    ).first()

    if not deed_template:
        return render(request, "core/legal/change_trustee_wizard.html", {
            "fy": fy,
            "entity": entity,
            "error": "No active Change of Trustee template found. Upload one in Legal Templates.",
        })

    # Pre-populate outgoing trustee from entity's current trustee
    outgoing_trustee = None
    if entity.trustee_name:
        outgoing_trustee = Entity.objects.filter(
            entity_name__iexact=entity.trustee_name,
            entity_type="company",
        ).first()

    # Get all company entities for the new trustee picker
    company_entities = Entity.objects.filter(
        entity_type="company",
    ).order_by("entity_name")

    # Eva clause pre-population
    clause_data = {"appointment_clause": "", "retirement_clause": ""}
    governing_doc = entity.governing_documents.filter(
        is_primary=True, status="active",
        extraction_status__in=["completed", "completed_with_warnings"],
    ).first()

    return render(request, "core/legal/change_trustee_wizard.html", {
        "fy": fy,
        "entity": entity,
        "deed_template": deed_template,
        "outgoing_trustee": outgoing_trustee,
        "company_entities": company_entities,
        "clause_data": clause_data,
        "governing_doc": governing_doc,
        "disclaimer": STANDARD_DISCLAIMER,
    })


@login_required
@require_POST
def change_of_trustee_generate(request, pk):
    """Generate Change of Trustee document set (3 documents)."""
    fy = get_financial_year_for_user(request, pk)
    entity = fy.entity

    if request.content_type == "application/json":
        params = json.loads(request.body)
    else:
        params = request.POST.dict()

    # Build context
    context = build_change_of_trustee_context(entity, fy, params)

    # Enrich with DocumentContextBuilder
    try:
        from core.document_context_builder import DocumentContextBuilder
        dcb = DocumentContextBuilder(entity, financial_year=fy, wizard_data=params)
        enriched = dcb.build("financial_statements")  # entity+practice context
        for k, v in enriched.items():
            if k not in context or k.startswith("practice_"):
                context[k] = v
    except Exception as _e:
        logger.warning("DCB enrichment skipped for change_of_trustee: %s", _e)

    # Define the 3 sub-documents
    template_configs = [
        {
            "template_type": "trust_deed_change_trustee",
            "sub_label": "Deed of Change of Trustee",
            "context_override": {"sub_document_type": "deed"},
        },
        {
            "template_type": "change_trustee_outgoing_resolution",
            "sub_label": "Outgoing Trustee Director Resolution",
            "context_override": {"sub_document_type": "outgoing_resolution"},
        },
        {
            "template_type": "change_trustee_new_minutes",
            "sub_label": "New Trustee Director Resolution",
            "context_override": {"sub_document_type": "new_trustee_minutes"},
        },
    ]

    result = render_multi_document_set(
        entity=entity,
        financial_year=fy,
        doc_type="trust_deed_change_trustee",
        context=context,
        params=params,
        user=request.user,
        template_configs=template_configs,
        disclaimer_acknowledged=params.get("disclaimer_acknowledged", False),
    )

    # Post-execution: update entity trustee fields
    if result["status"] == "ok":
        new_trustee_id = params.get("new_trustee_entity_id")
        if new_trustee_id:
            try:
                new_trustee = Entity.objects.get(pk=new_trustee_id)
                entity.trustee_name = new_trustee.entity_name
                entity.trustee_acn = new_trustee.acn or ""
                entity.save(update_fields=["trustee_name", "trustee_acn"])
            except Entity.DoesNotExist:
                pass

    return JsonResponse(result)


# ===========================================================================
# DOCUMENT 3: Fixed Unit Trust Deed + Ancillaries
# ===========================================================================

@login_required
def fixed_unit_trust_wizard(request, pk):
    """
    Fixed Unit Trust Deed + Ancillaries wizard — generates 5 documents:
      1. Unit Trust Deed
      2. Director Resolution (Trustee)
      3. Unit Applications (one per unitholder — looped)
      4. Unit Certificates (one per unitholder — looped)
      5. Register of Unitholders

    Wizard fields:
      1. Trust name (pre-populated)
      2. Trustee entity picker
      3. Governing state (dropdown)
      4. Deed date
      5. Unit class (default: "Ordinary")
      6. Unitholders (dynamic rows: entity picker + units)
    """
    fy = get_financial_year_for_user(request, pk)
    entity = fy.entity

    if entity.entity_type != "trust":
        return render(request, "core/legal/unit_trust_wizard.html", {
            "fy": fy,
            "entity": entity,
            "error": "Fixed Unit Trust Deed is only applicable to Trust entities.",
        })

    template = LegalDocumentTemplate.objects.filter(
        document_type="unit_trust_deed", is_active=True
    ).first()

    if not template:
        return render(request, "core/legal/unit_trust_wizard.html", {
            "fy": fy,
            "entity": entity,
            "error": "No active Fixed Unit Trust Deed template found. Upload one in Legal Templates.",
        })

    # Pre-populate trustee
    trustee_entity = None
    if entity.trustee_name:
        trustee_entity = Entity.objects.filter(
            entity_name__iexact=entity.trustee_name,
            entity_type="company",
        ).first()

    # Get all entities for unitholder picker
    all_entities = Entity.objects.filter(
        is_archived=False,
    ).order_by("entity_name")

    # States for governing state dropdown
    states = [
        ("NSW", "New South Wales"),
        ("VIC", "Victoria"),
        ("QLD", "Queensland"),
        ("SA", "South Australia"),
        ("WA", "Western Australia"),
        ("TAS", "Tasmania"),
        ("NT", "Northern Territory"),
        ("ACT", "Australian Capital Territory"),
    ]

    governing_doc = entity.governing_documents.filter(
        is_primary=True, status="active",
        extraction_status__in=["completed", "completed_with_warnings"],
    ).first()

    return render(request, "core/legal/unit_trust_wizard.html", {
        "fy": fy,
        "entity": entity,
        "template": template,
        "trustee_entity": trustee_entity,
        "all_entities": all_entities,
        "states": states,
        "governing_doc": governing_doc,
        "disclaimer": STANDARD_DISCLAIMER,
    })


@login_required
@require_POST
def fixed_unit_trust_generate(request, pk):
    """Generate Fixed Unit Trust Deed + Ancillaries (5 documents)."""
    fy = get_financial_year_for_user(request, pk)
    entity = fy.entity

    if request.content_type == "application/json":
        params = json.loads(request.body)
    else:
        params = request.POST.dict()
        # Parse unitholders from form data
        params["unitholders"] = _parse_unitholders_from_form(request.POST)

    # Pre-flight validation
    errors = validate_fixed_unit_trust(entity, params)
    if errors:
        return JsonResponse({"status": "error", "errors": errors}, status=400)

    # Build context
    context = build_fixed_unit_trust_context(entity, fy, params)

    # Enrich with DocumentContextBuilder
    try:
        from core.document_context_builder import DocumentContextBuilder
        dcb = DocumentContextBuilder(entity, financial_year=fy, wizard_data=params)
        enriched = dcb.build("financial_statements")
        for k, v in enriched.items():
            if k not in context or k.startswith("practice_"):
                context[k] = v
    except Exception as _e:
        logger.warning("DCB enrichment skipped for fixed_unit_trust: %s", _e)

    # Define the 5 sub-documents
    template_configs = [
        {
            "template_type": "unit_trust_deed",
            "sub_label": "Unit Trust Deed",
            "context_override": {"sub_document_type": "deed"},
        },
        {
            "template_type": "unit_trust_director_resolution",
            "sub_label": "Director Resolution (Trustee)",
            "context_override": {"sub_document_type": "director_resolution"},
        },
        {
            "template_type": "unit_trust_application",
            "sub_label": "Unit Applications",
            "context_override": {"sub_document_type": "unit_application"},
        },
        {
            "template_type": "unit_trust_certificate",
            "sub_label": "Unit Certificates",
            "context_override": {"sub_document_type": "unit_certificate"},
        },
        {
            "template_type": "unit_trust_register",
            "sub_label": "Register of Unitholders",
            "context_override": {"sub_document_type": "register"},
        },
    ]

    result = render_multi_document_set(
        entity=entity,
        financial_year=fy,
        doc_type="unit_trust_deed",
        context=context,
        params=params,
        user=request.user,
        template_configs=template_configs,
        disclaimer_acknowledged=params.get("disclaimer_acknowledged", False),
    )

    return JsonResponse(result)


# ===========================================================================
# DOCUMENT 4: Unit Transfer Package
# ===========================================================================

@login_required
def unit_transfer_wizard(request, pk):
    """
    Unit Transfer Package wizard — generates 7 documents:
      1. Cover Page
      2. Director Resolution (Trustee)
      3. Unit Transfer Instrument(s) — one per transfer
      4. Transferor Acknowledgements
      5. Transferee Acknowledgements
      6. Updated Unit Certificate(s)
      7. Updated Register of Unitholders

    Wizard fields:
      1. Trust entity (pre-populated)
      2. Unit class (pre-populated)
      3. Dynamic transfer rows:
         - Transferor (entity picker from current unitholders)
         - Transferee (entity picker or new name)
         - Units to transfer
         - Consideration amount
         - Transfer date
    """
    fy = get_financial_year_for_user(request, pk)
    entity = fy.entity

    if entity.entity_type != "trust":
        return render(request, "core/legal/unit_transfer_wizard.html", {
            "fy": fy,
            "entity": entity,
            "error": "Unit Transfer is only applicable to Trust entities.",
        })

    template = LegalDocumentTemplate.objects.filter(
        document_type="unit_transfer", is_active=True
    ).first()

    if not template:
        return render(request, "core/legal/unit_transfer_wizard.html", {
            "fy": fy,
            "entity": entity,
            "error": "No active Unit Transfer template found. Upload one in Legal Templates.",
        })

    # Get current unitholders (beneficiaries with shares_held)
    current_unitholders = EntityOfficer.objects.filter(
        entity=entity,
        date_ceased__isnull=True,
    ).filter(
        Q(role="beneficiary") | Q(roles__contains=["beneficiary"])
    ).filter(
        shares_held__isnull=False,
        shares_held__gt=0,
    ).order_by("full_name")

    # Get all entities for transferee picker
    all_entities = Entity.objects.filter(
        is_archived=False,
    ).order_by("entity_name")

    governing_doc = entity.governing_documents.filter(
        is_primary=True, status="active",
        extraction_status__in=["completed", "completed_with_warnings"],
    ).first()

    return render(request, "core/legal/unit_transfer_wizard.html", {
        "fy": fy,
        "entity": entity,
        "template": template,
        "current_unitholders": current_unitholders,
        "all_entities": all_entities,
        "governing_doc": governing_doc,
        "disclaimer": STANDARD_DISCLAIMER,
    })


@login_required
@require_POST
def unit_transfer_generate(request, pk):
    """Generate Unit Transfer Package (7 documents)."""
    fy = get_financial_year_for_user(request, pk)
    entity = fy.entity

    if request.content_type == "application/json":
        params = json.loads(request.body)
    else:
        params = request.POST.dict()
        params["transfers"] = _parse_transfers_from_form(request.POST)

    # Build context
    context = build_unit_transfer_context(entity, fy, params)

    # Enrich with DocumentContextBuilder
    try:
        from core.document_context_builder import DocumentContextBuilder
        dcb = DocumentContextBuilder(entity, financial_year=fy, wizard_data=params)
        enriched = dcb.build("financial_statements")
        for k, v in enriched.items():
            if k not in context or k.startswith("practice_"):
                context[k] = v
    except Exception as _e:
        logger.warning("DCB enrichment skipped for unit_transfer: %s", _e)

    # Define the 7 sub-documents
    template_configs = [
        {
            "template_type": "unit_transfer_cover",
            "sub_label": "Cover Page",
            "context_override": {"sub_document_type": "cover"},
        },
        {
            "template_type": "unit_transfer_director_resolution",
            "sub_label": "Director Resolution (Trustee)",
            "context_override": {"sub_document_type": "director_resolution"},
        },
        {
            "template_type": "unit_transfer_instrument",
            "sub_label": "Unit Transfer Instrument(s)",
            "context_override": {"sub_document_type": "transfer_instrument"},
        },
        {
            "template_type": "unit_transfer_transferor_ack",
            "sub_label": "Transferor Acknowledgements",
            "context_override": {"sub_document_type": "transferor_acknowledgement"},
        },
        {
            "template_type": "unit_transfer_transferee_ack",
            "sub_label": "Transferee Acknowledgements",
            "context_override": {"sub_document_type": "transferee_acknowledgement"},
        },
        {
            "template_type": "unit_transfer_certificate",
            "sub_label": "Updated Unit Certificates",
            "context_override": {"sub_document_type": "certificate"},
        },
        {
            "template_type": "unit_transfer_register",
            "sub_label": "Updated Register of Unitholders",
            "context_override": {"sub_document_type": "register"},
        },
    ]

    result = render_multi_document_set(
        entity=entity,
        financial_year=fy,
        doc_type="unit_transfer",
        context=context,
        params=params,
        user=request.user,
        template_configs=template_configs,
        disclaimer_acknowledged=params.get("disclaimer_acknowledged", False),
    )

    # Post-execution: prompt accountant to update unitholder records
    if result["status"] in ("ok", "partial"):
        result["post_execution_prompt"] = (
            "Unit transfer documents generated. Please update the entity's "
            "unitholder records (Officers tab) to reflect the new ownership structure."
        )

    return JsonResponse(result)


# ---------------------------------------------------------------------------
# Document Download
# ---------------------------------------------------------------------------
@login_required
def legal_doc_download(request, doc_pk, fmt="docx"):
    """Download a generated legal document."""
    doc = get_object_or_404(LegalDocument, pk=doc_pk)
    get_entity_for_user(request, doc.entity_id)

    if fmt == "pdf" and doc.pdf_file:
        return FileResponse(doc.pdf_file.open(), content_type="application/pdf",
                            as_attachment=True, filename=os.path.basename(doc.pdf_file.name))
    elif doc.generated_file:
        return FileResponse(
            doc.generated_file.open(),
            content_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            as_attachment=True,
            filename=os.path.basename(doc.generated_file.name),
        )
    else:
        return JsonResponse({"error": "File not found."}, status=404)


# ---------------------------------------------------------------------------
# Document List (per FY)
# ---------------------------------------------------------------------------
@login_required
def legal_doc_list(request, pk):
    """List all generated legal documents for a financial year."""
    fy = get_financial_year_for_user(request, pk)
    documents = LegalDocument.objects.filter(financial_year=fy).order_by("-generated_at")
    return JsonResponse({
        "documents": [
            {
                "id": str(d.pk),
                "document_type": d.document_type,
                "document_type_display": d.get_document_type_display(),
                "status": d.status,
                "version": d.version,
                "generated_at": d.generated_at.isoformat(),
                "generated_by": d.generated_by.get_full_name() if d.generated_by else "",
                "docx_url": d.generated_file.url if d.generated_file else None,
                "pdf_url": d.pdf_file.url if d.pdf_file else None,
                "fusesign_status": d.fusesign_status,
            }
            for d in documents
        ]
    })


# ---------------------------------------------------------------------------
# FuseSign Integration
# ---------------------------------------------------------------------------
@login_required
@require_POST
def legal_doc_send_fusesign(request, doc_pk):
    """Send a generated document to FuseSign for electronic signing."""
    doc = get_object_or_404(LegalDocument, pk=doc_pk)
    get_entity_for_user(request, doc.entity_id)

    if not doc.pdf_file:
        return JsonResponse({"error": "PDF file required for FuseSign."}, status=400)

    fusesign_api_key = getattr(settings, "FUSESIGN_API_KEY", "")
    fusesign_base_url = getattr(settings, "FUSESIGN_BASE_URL", "")

    if not fusesign_api_key or not fusesign_base_url:
        return JsonResponse(
            {"error": "FuseSign is not configured. Set FUSESIGN_API_KEY and FUSESIGN_BASE_URL in settings."},
            status=400,
        )

    try:
        import requests as http_requests

        # Get document-type-specific signatories
        signatories = _get_signatories_for_doc(doc)
        if not signatories:
            return JsonResponse({"error": "No signatories found for this document."}, status=400)

        entity_name = doc.entity.entity_name if doc.entity else "Unknown"

        # Create FuseSign envelope
        payload = {
            "title": f"{doc.get_document_type_display()} — {entity_name}",
            "message": f"Please review and sign the attached {doc.get_document_type_display()}.",
            "signers": [
                {
                    "name": s["name"],
                    "email": s["email"],
                    "order": idx + 1,
                }
                for idx, s in enumerate(signatories)
            ],
        }

        # Upload document
        headers = {
            "Authorization": f"Bearer {fusesign_api_key}",
        }

        resp = http_requests.post(
            f"{fusesign_base_url}/api/v1/envelopes",
            json=payload,
            headers=headers,
            timeout=30,
        )
        resp.raise_for_status()
        envelope_data = resp.json()

        # Upload the PDF to the envelope
        doc.pdf_file.seek(0)
        files_resp = http_requests.post(
            f"{fusesign_base_url}/api/v1/envelopes/{envelope_data['id']}/documents",
            files={"file": (os.path.basename(doc.pdf_file.name), doc.pdf_file.read(), "application/pdf")},
            headers=headers,
            timeout=60,
        )
        files_resp.raise_for_status()

        # Send the envelope
        send_resp = http_requests.post(
            f"{fusesign_base_url}/api/v1/envelopes/{envelope_data['id']}/send",
            headers=headers,
            timeout=30,
        )
        send_resp.raise_for_status()

        doc.fusesign_envelope_id = envelope_data["id"]
        doc.fusesign_status = LegalDocument.FuseSignStatus.SENT
        doc.save(update_fields=["fusesign_envelope_id", "fusesign_status"])

        # Log activity
        log_fusesign_activity(doc, request.user, len(signatories), envelope_data["id"])

        return JsonResponse({
            "status": "ok",
            "envelope_id": envelope_data["id"],
            "message": f"Document sent to {len(signatories)} signer(s) via FuseSign.",
        })

    except Exception as e:
        logger.exception("FuseSign send failed: %s", e)
        return JsonResponse({"error": str(e)}, status=500)


# ---------------------------------------------------------------------------
# Entity Search API (for wizard entity pickers)
# ---------------------------------------------------------------------------
@login_required
def legal_doc_entity_search(request):
    """
    HTMX-compatible entity search for wizard entity pickers.
    Returns JSON list of matching entities.
    """
    q = request.GET.get("q", "").strip()
    entity_type = request.GET.get("entity_type", "")
    limit = int(request.GET.get("limit", "20"))

    qs = Entity.objects.filter(is_archived=False)
    if q:
        qs = qs.filter(
            Q(entity_name__icontains=q) | Q(acn__icontains=q) | Q(abn__icontains=q)
        )
    if entity_type:
        qs = qs.filter(entity_type=entity_type)

    entities = qs.order_by("entity_name")[:limit]

    return JsonResponse({
        "results": [
            {
                "id": str(e.pk),
                "name": e.entity_name,
                "type": e.get_entity_type_display(),
                "acn": e.acn or "",
                "abn": e.abn or "",
            }
            for e in entities
        ]
    })


# ---------------------------------------------------------------------------
# Internal Helpers
# ---------------------------------------------------------------------------
def _build_entity_context(entity, fy):
    """Build a template context dict from entity and FY data."""
    officers = EntityOfficer.objects.filter(entity=entity, date_ceased__isnull=True)
    directors = officers.filter(
        Q(role__in=["director", "sole_director"]) | Q(roles__overlap=["director"])
    )
    shareholders = officers.filter(
        Q(role__in=["shareholder", "director_shareholder"]) | Q(roles__overlap=["shareholder"])
    )

    context = {
        # Entity
        "entity_name": entity.entity_name,
        "entity_type": entity.get_entity_type_display() if hasattr(entity, "get_entity_type_display") else entity.entity_type,
        "abn": entity.abn or "",
        "acn": entity.acn or "",
        "tfn": entity.tfn or "",
        "address": _get_entity_address(entity),
        "state": entity.state or "",
        # Financial Year
        "fy_start_date": fy.start_date.strftime("%d %B %Y"),
        "fy_end_date": fy.end_date.strftime("%d %B %Y"),
        "fy_year": str(fy.end_date.year),
        "fy_label": f"{fy.start_date.strftime('%d %B %Y')} to {fy.end_date.strftime('%d %B %Y')}",
        # Officers
        "directors": [
            {
                "name": o.full_name,
                "role": o.roles_display if o.roles else o.get_role_display(),
                "date_appointed": o.date_appointed.strftime("%d %B %Y") if o.date_appointed else "",
                "shares_held": str(o.shares_held) if hasattr(o, "shares_held") and o.shares_held else "",
            }
            for o in directors
        ],
        "shareholders": [
            {
                "name": o.full_name,
                "shares_held": str(o.shares_held) if hasattr(o, "shares_held") and o.shares_held else "",
            }
            for o in shareholders
        ],
        "all_officers": [
            {"name": o.full_name, "role": o.roles_display if o.roles else o.get_role_display()}
            for o in officers
        ],
        # Trust-specific
        "trustee_name": entity.trustee_name or "",
        "trustee_acn": entity.trustee_acn or "",
        "deed_date": entity.deed_date.strftime("%d %B %Y") if entity.deed_date else "",
        "vesting_date": entity.vesting_date.strftime("%d %B %Y") if entity.vesting_date else "",
        # Company-specific
        "total_shares_on_issue": str(entity.total_shares_on_issue) if entity.total_shares_on_issue else "",
        "is_large_proprietary": getattr(entity, "is_large_proprietary", False),
    }

    return context


def _extract_template_variables(template):
    """Extract {{variable}} placeholders from a docxtpl template."""
    import re
    try:
        from docxtpl import DocxTemplate
        tpl = DocxTemplate(template.template_file.path)
        # Get the XML content
        xml_content = tpl.get_xml()
        # Find all {{variable}} patterns
        variables = set(re.findall(r'\{\{([\w.]+)\}\}', xml_content))
        # Also find {% for %} loop variables
        loops = re.findall(r'\{%\s*for\s+(\w+)\s+in\s+(\w+)\s*%\}', xml_content)

        schema = {
            "variables": sorted(variables),
            "loops": [{"item": l[0], "collection": l[1]} for l in loops],
        }
        return schema
    except Exception as e:
        logger.warning("Failed to extract template variables: %s", e)
        return {"variables": [], "loops": []}


def _get_signatories_for_doc(doc):
    """
    Get document-type-specific signatories for FuseSign.
    Uses the stored parameters to determine the correct signatory list.
    """
    params = doc.parameters or {}
    entity = doc.entity

    SIGNATORY_BUILDERS = {
        "div7a_loan_agreement": get_div7a_signatories,
        "trust_deed_change_trustee": get_change_of_trustee_signatories,
        "change_trustee_outgoing_resolution": get_change_of_trustee_signatories,
        "change_trustee_new_minutes": get_change_of_trustee_signatories,
        "unit_trust_deed": get_fixed_unit_trust_signatories,
        "unit_trust_director_resolution": get_fixed_unit_trust_signatories,
        "unit_trust_application": get_fixed_unit_trust_signatories,
        "unit_trust_certificate": get_fixed_unit_trust_signatories,
        "unit_trust_register": get_fixed_unit_trust_signatories,
        "unit_transfer": get_unit_transfer_signatories,
        "unit_transfer_cover": get_unit_transfer_signatories,
        "unit_transfer_director_resolution": get_unit_transfer_signatories,
        "unit_transfer_instrument": get_unit_transfer_signatories,
        "unit_transfer_transferor_ack": get_unit_transfer_signatories,
        "unit_transfer_transferee_ack": get_unit_transfer_signatories,
        "unit_transfer_certificate": get_unit_transfer_signatories,
        "unit_transfer_register": get_unit_transfer_signatories,
    }

    builder = SIGNATORY_BUILDERS.get(doc.document_type)
    if builder:
        return builder(entity, params)

    # Fallback: get directors with email
    return _get_default_signatories(entity)


def _get_default_signatories(entity):
    """Fallback signatory list: active directors with email addresses."""
    directors = _get_directors_for_entity(entity)
    signatories = []
    for d in directors:
        email = d.email or ""
        if email:
            signatories.append({"name": d.full_name, "email": email})
    return signatories


def _parse_unitholders_from_form(post_data):
    """Parse unitholder rows from form POST data."""
    unitholders = []
    idx = 0
    while True:
        entity_id = post_data.get(f"unitholder_{idx}_entity_id")
        entity_name = post_data.get(f"unitholder_{idx}_name", "")
        units = post_data.get(f"unitholder_{idx}_units", "0")
        is_trustee = post_data.get(f"unitholder_{idx}_is_trustee", "") == "true"

        if not entity_id and not entity_name:
            break

        unitholders.append({
            "entity_id": entity_id,
            "entity_name": entity_name,
            "units": units,
            "is_trustee": is_trustee,
        })
        idx += 1

    return unitholders


def _parse_transfers_from_form(post_data):
    """Parse transfer rows from form POST data."""
    transfers = []
    idx = 0
    while True:
        transferor_id = post_data.get(f"transfer_{idx}_transferor_entity_id")
        transferee_id = post_data.get(f"transfer_{idx}_transferee_entity_id", "")
        transferee_name = post_data.get(f"transfer_{idx}_transferee_name", "")
        units = post_data.get(f"transfer_{idx}_units", "0")
        consideration = post_data.get(f"transfer_{idx}_consideration", "0")
        transfer_date = post_data.get(f"transfer_{idx}_date", "")

        if not transferor_id:
            break

        transfers.append({
            "transferor_entity_id": transferor_id,
            "transferee_entity_id": transferee_id or None,
            "transferee_name": transferee_name,
            "units": units,
            "consideration": consideration,
            "transfer_date": transfer_date,
        })
        idx += 1

    return transfers
