# Generated by Django 5.2.11 on 2026-03-02 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_asicreturn_basperiodcommentary_correspondence_and_more'),
        ('review', '0006_enhanced_review_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitygstsetting',
            name='financial_year',
            field=models.ForeignKey(blank=True, help_text='If null, applies to all financial years', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_gst_settings', to='core.financialyear'),
        ),
    ]
