# Generated by Django 5.2.11 on 2026-03-11 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_alter_entity_contact_phone_alter_entity_tfn_and_more"),
        ("review", "0010_merge_server_0007"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitygstsetting",
            name="financial_year",
            field=models.ForeignKey(
                blank=True,
                help_text="If null, applies to all financial years",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity_gst_settings",
                to="core.financialyear",
            ),
        ),
    ]
