# Generated by Django 5.2.11 on 2026-03-11 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_entitygstsetting_financial_year'),
        ('review', '0011_alter_entitygstsetting_financial_year'),
    ]

    operations = [
    ]
