# Generated by Django 5.2.11 on 2026-08-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_reviewjob_financial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewjob',
            name='override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewjob',
            name='override_by',
            field=models.CharField(blank=True, default='', help_text='Who imported it over the failed check', max_length=255),
        ),
        migrations.AddField(
            model_name='reviewjob',
            name='override_reason',
            field=models.TextField(blank=True, default='', help_text='Why this statement was imported despite failing the check'),
        ),
        migrations.AddField(
            model_name='reviewjob',
            name='verification_detail',
            field=models.TextField(blank=True, default='', help_text='What the import check objected to, if anything'),
        ),
        migrations.AddField(
            model_name='reviewjob',
            name='verification_status',
            field=models.CharField(choices=[('verified', 'Verified against its own balances'), ('overridden', 'Imported over a failed verification')], default='verified', help_text='Whether this statement passed the import balance checks', max_length=20),
        ),
    ]
