# Generated by Django 5.2.11 on 2026-03-11 00:37

import config.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_alter_accountingconnection_access_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myobcompanyfile",
            name="cf_password",
            field=config.encryption.EncryptedCharField(
                blank=True,
                default="",
                help_text="Company file password (encrypted at rest)",
            ),
        ),
        migrations.AlterField(
            model_name="myobcompanyfile",
            name="cf_username",
            field=config.encryption.EncryptedCharField(
                blank=True, default="Administrator", help_text="Company file username"
            ),
        ),
    ]
